module fuzz

import globset

// fuzz_glob is the ownership-mode entry point corresponding to the
// `libfuzzer_sys::fuzz_target!` generated by the Rust source.
pub fn fuzz_glob(glob_str string) {
	glob := globset.Glob.new(glob_str) or { return }
	glob2 := globset.Glob.from_str(glob_str) or { return }

	// Verify that a `Glob` constructed with `new` is the same as a `Glob`` constructed
	// with `from_str`.
	assert glob == glob2

	// Verify that `Glob::glob` produces the same string as the original.
	assert *glob.glob() == glob_str
}
