module regex

import matcher
import regex.pcre

/// Config represents the configuration of a regex matcher in this crate.
/// The configuration is itself a rough combination of the knobs found in
/// the `regex` crate itself, along with additional `grep-matcher` specific
/// options.
///
/// The configuration can be used to build a "configured" HIR expression. A
/// configured HIR expression is an HIR expression that is aware of the
/// configuration which generated it, and provides transformation on that HIR
/// such that the configuration is preserved.
pub struct Config implements IClone {
pub mut:
	case_insensitive     bool
	case_smart           bool
	multi_line           bool
	dot_matches_new_line bool
	swap_greed           bool
	ignore_whitespace    bool
	unicode              bool
	octal                bool
	size_limit           usize
	dfa_size_limit       usize
	nest_limit           u32
	line_terminator      ?matcher.LineTerminator
	ban                  ?u8
	crlf                 bool
	word                 bool
	fixed_strings        bool
	whole_line           bool
}

pub fn Config.default() Config {
	return Config{
		unicode:        true
		size_limit:     usize(100 * (1 << 20))
		dfa_size_limit: usize(1000 * (1 << 20))
		nest_limit:     u32(250)
		line_terminator: none
		ban:             none
	}
}

// V-specific: keep an explicit clone while V2 mark-used/codegen can resolve
// generated clone helpers for same-named structs across modules inconsistently.
pub fn (config Config) clone() Config {
	return Config{
		case_insensitive:     config.case_insensitive
		case_smart:           config.case_smart
		multi_line:           config.multi_line
		dot_matches_new_line: config.dot_matches_new_line
		swap_greed:           config.swap_greed
		ignore_whitespace:    config.ignore_whitespace
		unicode:              config.unicode
		octal:                config.octal
		size_limit:           config.size_limit
		dfa_size_limit:       config.dfa_size_limit
		nest_limit:           config.nest_limit
		line_terminator:      config.line_terminator
		ban:                  config.ban
		crlf:                 config.crlf
		word:                 config.word
		fixed_strings:        config.fixed_strings
		whole_line:           config.whole_line
	}
}

/// Use this configuration to build an HIR from the given patterns. The HIR
/// returned corresponds to a single regex that is an alternation of the
/// patterns given.
pub fn (config Config) build_many(patterns []string) !ConfiguredHIR {
	return ConfiguredHIR.new(config.clone(), patterns)
}

/// Accounting for the `smart_case` config knob, return true if and only if
/// this pattern should be matched case insensitively.
fn (config Config) is_case_insensitive(analysis AstAnalysis) bool {
	if config.case_insensitive {
		return true
	}
	if !config.case_smart {
		return false
	}
	return analysis.any_literal() && !analysis.any_uppercase()
}

/// Returns whether the given patterns should be treated as "fixed strings"
/// literals. This is different from just querying the `fixed_strings` knob
/// in that if the knob is false, this will still return true in some cases
/// if the patterns are themselves indistinguishable from literals.
///
/// The main idea here is that if this returns true, then it is safe
/// to build an `regex_syntax::hir::Hir` value directly from the given
/// patterns as an alternation of `hir::Literal` values.
fn (config Config) is_fixed_strings(patterns []string) bool {
	// When these are enabled, we really need to parse the patterns and
	// let them go through the standard HIR translation process in order
	// for case folding transforms to be applied.
	if config.case_insensitive || config.case_smart {
		return false
	}
	// Even if whole_line or word is enabled, both of those things can
	// be implemented by wrapping the Hir generated by an alternation of
	// fixed string literals. So for here at least, we don't care about the
	// word or whole_line settings.
	if config.fixed_strings {
		// ... but if any literal contains a line terminator, then we've
		// got to bail out because this will ultimately result in an error.
		if lineterm := config.line_terminator {
			for p in patterns {
				if has_line_terminator(lineterm, p) {
					return false
				}
			}
		}
		return true
	}
	// In this case, the only way we can hand construct the Hir is if none
	// of the patterns contain meta characters. If they do, then we need to
	// send them through the standard parsing/translation process.
	for p in patterns {
		for ch in p {
			if is_regex_meta_character(ch) {
				return false
			}
		}
		// Same deal as when fixed_strings is set above. If the pattern has
		// a line terminator anywhere, then we need to bail out and let
		// an error occur.
		if lineterm := config.line_terminator {
			if has_line_terminator(lineterm, p) {
				return false
			}
		}
	}
	return true
}

/// A "configured" HIR expression, which is aware of the configuration which
/// produced this HIR.
///
/// Since the configuration is tracked, values with this type can be
/// transformed into other HIR expressions (or regular expressions) in a way
/// that preserves the configuration. For example, the `fast_line_regex`
/// method will apply literal extraction to the inner HIR and use that to build
/// a new regex that matches the extracted literals in a way that is
/// consistent with the configuration that produced this HIR. For example, the
/// size limits set on the configured HIR will be propagated out to any
/// subsequently constructed HIR or regular expression.
pub struct ConfiguredHIR implements IClone {
	config Config
	hir    Hir
}

/// Parse the given patterns into a single HIR expression that represents
/// an alternation of the patterns given.
fn ConfiguredHIR.new(config Config, patterns []string) !ConfiguredHIR {
	mut hir := Hir.empty()
	if config.is_fixed_strings(patterns) {
		hir = Hir.from_fixed_literals(patterns)
	} else {
		mut alts := []string{cap: patterns.len}
		for p in patterns {
			if config.fixed_strings {
				alts << '(?:${escape_regex(p)})'
			} else {
				alts << '(?:${p})'
			}
		}
		mut pattern := if alts.len == 0 { '' } else { alts.join('|') }
		if config.ignore_whitespace {
			pattern = strip_ignored_whitespace(pattern)
		}
		hir = Hir.from_pattern(pattern, config)
	}
	if banned := config.ban {
		ban_check(hir.to_regex(), banned)!
	}
	if line_term := config.line_terminator {
		stripped := strip_line_terminator_from_match(hir.to_regex(), line_term)!
		hir = Hir.from_pattern(stripped, config)
	}
	return ConfiguredHIR{
		config: config
		hir:    hir
	}
}

/// Return a reference to the underlying configuration.
pub fn (chir &^a ConfiguredHIR) config[^a]() &^a Config {
	return &chir.config
}

/// Return a reference to the underlying HIR.
pub fn (chir &^a ConfiguredHIR) hir[^a]() &^a Hir {
	return &chir.hir
}

/// Convert this HIR to a regex that can be used for matching.
pub fn (chir ConfiguredHIR) to_regex() !pcre.Regex {
	pattern := chir.backend_pattern()
	return pcre.compile(pattern) or { return Error.regex(err.msg()) }
}

/// Compute the set of non-matching bytes for this HIR expression.
pub fn (chir ConfiguredHIR) non_matching_bytes() matcher.ByteSet {
	return chir.hir.non_matching_bytes()
}

/// Returns the line terminator configured on this expression.
///
/// When we have beginning/end anchors (NOT line anchors), the fast line
/// searching path isn't quite correct. Or at least, doesn't match the slow
/// path. Namely, the slow path strips line terminators while the fast path
/// does not. Since '$' (when multi-line mode is disabled) doesn't match at
/// line boundaries, the existence of a line terminator might cause it to
/// not match when it otherwise would with the line terminator stripped.
///
/// Since searching with text anchors is exceptionally rare in the context
/// of line oriented searching (multi-line mode is basically always
/// enabled), we just disable this optimization when there are text
/// anchors. We disable it by not returning a line terminator, since
/// without a line terminator, the fast search path can't be executed.
///
/// Actually, the above is no longer quite correct. Later on, another
/// optimization was added where if the line terminator was in the set of
/// bytes that was guaranteed to never be part of a match, then the higher
/// level search infrastructure assumes that the fast line-by-line search
/// path can still be taken. This optimization applies when multi-line
/// search (not multi-line mode) is enabled. In that case, there is no
/// configured line terminator since the regex is permitted to match a
/// line terminator. But if the regex is guaranteed to never match across
/// multiple lines despite multi-line search being requested, we can still
/// do the faster and more flexible line-by-line search. This is why the
/// non-matching extraction routine removes `\n` when `\A` and `\z` are
/// present even though that's not quite correct...
///
/// See: <https://github.com/BurntSushi/ripgrep/issues/2260>
pub fn (chir ConfiguredHIR) line_terminator() ?matcher.LineTerminator {
	if chir.hir.contains_haystack_anchor() {
		return none
	}
	return chir.config.line_terminator
}

/// Turns this configured HIR into an equivalent one, but where it must
/// match at the start and end of a line.
pub fn (chir ConfiguredHIR) into_whole_line() ConfiguredHIR {
	return ConfiguredHIR{
		config: chir.config.clone()
		hir:    chir.hir.into_whole_line(chir.config)
	}
}

/// Turns this configured HIR into an equivalent one, but where it must
/// match at word boundaries.
pub fn (chir ConfiguredHIR) into_word() ConfiguredHIR {
	// V-specific: the local backend does not reliably support the look-around
	// assertions needed for half-word boundaries without changing match
	// offsets, so word-boundary enforcement is applied by
	// RegexMatcher.accept_match.
	return chir
}

fn (chir ConfiguredHIR) backend_pattern() string {
	mut flags := ''
	pattern := normalize_backend_pattern(chir.hir.to_regex(), chir.config)
	analysis := AstAnalysis.from_pattern(pattern) or { AstAnalysis.new() }
	if chir.config.is_case_insensitive(analysis) {
		flags += 'i'
	}
	if chir.config.multi_line || chir.config.crlf {
		flags += 'm'
	}
	if chir.config.dot_matches_new_line {
		flags += 's'
	}
	if flags.len == 0 {
		return pattern
	}
	return '(?${flags})${pattern}'
}

fn normalize_backend_pattern(pattern string, config Config) string {
	mut out := []u8{cap: pattern.len}
	mut i := 0
	mut in_class := false
	mut escaped := false
	for i < pattern.len {
		ch := pattern[i]
		if config.crlf && !escaped && !in_class && ch == `$` {
			out << r'\x0D?$'.bytes()
			i++
			continue
		}
		if !escaped && ch == `[` {
			in_class = true
		} else if !escaped && ch == `]` {
			in_class = false
		}
		if !escaped && i + 7 <= pattern.len && ch == `\\` && pattern[i + 2] == `{`
			&& pattern[i + 3..i + 6] == 'Any' && pattern[i + 6] == `}` {
			if pattern[i + 1] == `p` {
				out << '(?:.|\n|\r)'.bytes()
				i += 7
				escaped = false
				continue
			}
			if pattern[i + 1] == `P` {
				out << r'(?!)'.bytes()
				i += 7
				escaped = false
				continue
			}
		}
		out << ch
		escaped = !escaped && ch == `\\`
		i++
	}
	return out.bytestr()
}

/// Returns true if the given literal string contains any byte from the line
/// terminator given.
fn has_line_terminator(lineterm matcher.LineTerminator, literal string) bool {
	if lineterm.is_crlf() {
		return literal.contains_u8(`\r`) || literal.contains_u8(`\n`)
	}
	return literal.contains_u8(lineterm.as_byte())
}

fn is_regex_meta_character(ch rune) bool {
	return ch in [`\\`, `.`, `+`, `*`, `?`, `(`, `)`, `|`, `[`, `]`, `{`, `}`, `^`, `$`,
		`#`, `&`, `-`, `~`]
}

fn escape_regex(literal string) string {
	mut out := []u8{cap: literal.len}
	for byte in literal.bytes() {
		match byte {
			`\\`, `.`, `+`, `*`, `?`, `(`, `)`, `|`, `[`, `]`, `{`, `}`, `^`, `$`, `#`,
			`&`, `-`, `~` {
				out << `\\`
				out << byte
			}
			else {
				out << byte
			}
		}
	}
	return out.bytestr()
}

fn strip_ignored_whitespace(pattern string) string {
	mut out := []u8{cap: pattern.len}
	mut i := 0
	mut in_class := false
	mut escaped := false
	for i < pattern.len {
		byte := pattern[i]
		if escaped {
			out << byte
			escaped = false
			i++
			continue
		}
		if byte == `\\` {
			out << byte
			escaped = true
			i++
			continue
		}
		if byte == `[` {
			in_class = true
			out << byte
			i++
			continue
		}
		if byte == `]` {
			in_class = false
			out << byte
			i++
			continue
		}
		if !in_class && byte == `#` {
			for i < pattern.len && pattern[i] != `\n` {
				i++
			}
			continue
		}
		if !in_class && byte in [` `, `\t`, `\n`, `\r`, `\v`, `\f`] {
			i++
			continue
		}
		out << byte
		i++
	}
	return out.bytestr()
}

fn ban_check(pattern string, byte u8) ! {
	mut i := 0
	for i < pattern.len {
		if pattern[i] == byte {
			return Error.new(ErrorKind.banned(byte))
		}
		if pattern[i] == `[` {
			class_set, ok, class_pos := parse_class_set(pattern, i + 1)
			if ok {
				mut count := 0
				for present in class_set {
					if present {
						count++
					}
				}
				if count == 1 && class_set[int(byte)] {
					return Error.new(ErrorKind.banned(byte))
				}
				i = class_pos
				continue
			}
		}
		if pattern[i] == `\\` {
			has_byte, escaped, next := parse_escape_byte(pattern, i)
			if has_byte && escaped == byte {
				return Error.new(ErrorKind.banned(byte))
			}
			i = next
			continue
		}
		i++
	}
}

struct ClassAtom {
	set        []bool
	single     u8
	has_single bool
	ok         bool
}

fn parse_class_set(pattern string, start int) ([]bool, bool, int) {
	mut i := start
	mut negated := false
	if i < pattern.len && pattern[i] == `^` {
		negated = true
		i++
	}
	mut set := empty_byte_class()
	for i < pattern.len {
		if pattern[i] == `]` {
			i++
			if negated {
				invert_byte_class(mut set)
			}
			return set, true, i
		}
		start_atom, next_i := parse_class_atom(pattern, i)
		i = next_i
		if !start_atom.ok {
			return set, false, i
		}
		if i < pattern.len && pattern[i] == `-` && i + 1 < pattern.len && pattern[i + 1] != `]` {
			i++
			end_atom, after_end := parse_class_atom(pattern, i)
			i = after_end
			if !end_atom.ok {
				return set, false, i
			}
			if start_atom.has_single && end_atom.has_single {
				add_byte_range(mut set, start_atom.single, end_atom.single)
			} else {
				add_byte_class(mut set, start_atom.set)
				add_byte_class(mut set, end_atom.set)
			}
		} else {
			add_byte_class(mut set, start_atom.set)
		}
	}
	return set, false, i
}

fn parse_class_atom(pattern string, i int) (ClassAtom, int) {
	if i >= pattern.len {
		return ClassAtom{}, i
	}
	if pattern[i] == `[` {
		nested, ok, next := parse_class_set(pattern, i + 1)
		return ClassAtom{
			set: nested
			ok:  ok
		}, next
	}
	if pattern[i] == `\\` {
		set, has_single, single, ok, next := parse_escape_class(pattern, i)
		return ClassAtom{
			set:        set
			single:     single
			has_single: has_single
			ok:         ok
		}, next
	}
	byte := pattern[i]
	mut set := empty_byte_class()
	set[int(byte)] = true
	return ClassAtom{
		set:        set
		single:     byte
		has_single: true
		ok:         true
	}, i + 1
}

fn parse_escape_class(pattern string, i int) ([]bool, bool, u8, bool, int) {
	if i + 1 >= pattern.len {
		return full_byte_class(), false, u8(0), false, pattern.len
	}
	next := pattern[i + 1]
	match next {
		`d` {
			mut set := empty_byte_class()
			add_byte_range(mut set, `0`, `9`)
			return set, false, u8(0), true, i + 2
		}
		`D` {
			mut set := full_byte_class()
			for byte := `0`; byte <= `9`; byte++ {
				set[int(byte)] = false
			}
			return set, false, u8(0), true, i + 2
		}
		`s` {
			mut set := empty_byte_class()
			for byte in [`\t`, `\n`, 0x0b, 0x0c, `\r`, ` `] {
				set[int(byte)] = true
			}
			return set, false, u8(0), true, i + 2
		}
		`S` {
			mut set := full_byte_class()
			for byte in [`\t`, `\n`, 0x0b, 0x0c, `\r`, ` `] {
				set[int(byte)] = false
			}
			return set, false, u8(0), true, i + 2
		}
		`w` {
			mut set := empty_byte_class()
			add_word_bytes(mut set)
			return set, false, u8(0), true, i + 2
		}
		`W` {
			mut set := full_byte_class()
			mut word := empty_byte_class()
			add_word_bytes(mut word)
			for index, present in word {
				if present {
					set[index] = false
				}
			}
			return set, false, u8(0), true, i + 2
		}
		else {
			has_byte, byte, next_i := parse_escape_byte(pattern, i)
			if !has_byte {
				return full_byte_class(), false, u8(0), true, next_i
			}
			mut set := empty_byte_class()
			set[int(byte)] = true
			return set, true, byte, true, next_i
		}
	}
}

fn parse_escape_byte(pattern string, i int) (bool, u8, int) {
	if i + 1 >= pattern.len {
		return false, u8(0), pattern.len
	}
	next := pattern[i + 1]
	if escaped := escaped_byte(next) {
		return true, escaped, i + 2
	}
	if next == `x` {
		if i + 2 < pattern.len && pattern[i + 2] == `{` {
			mut end := i + 3
			for end < pattern.len && pattern[end] != `}` {
				end++
			}
			if end < pattern.len {
				value := parse_hex_u32(pattern[i + 3..end]) or { return false, u8(0), end + 1 }
				if value <= 0xff {
					return true, u8(value), end + 1
				}
				return false, u8(0), end + 1
			}
		}
		if i + 4 <= pattern.len {
			value := parse_hex_u32(pattern[i + 2..i + 4]) or { return false, u8(0), i + 4 }
			if value <= 0xff {
				return true, u8(value), i + 4
			}
			return false, u8(0), i + 4
		}
	}
	if next == `u` {
		if i + 2 < pattern.len && pattern[i + 2] == `{` {
			mut end := i + 3
			for end < pattern.len && pattern[end] != `}` {
				end++
			}
			if end < pattern.len {
				value := parse_hex_u32(pattern[i + 3..end]) or { return false, u8(0), end + 1 }
				if value <= 0xff {
					return true, u8(value), end + 1
				}
				return false, u8(0), end + 1
			}
		}
		if i + 6 > pattern.len {
			return false, u8(0), pattern.len
		}
		value := parse_hex_u32(pattern[i + 2..i + 6]) or { return false, u8(0), i + 6 }
		if value <= 0xff {
			return true, u8(value), i + 6
		}
		return false, u8(0), i + 6
	}
	if next == `U` && i + 10 <= pattern.len {
		value := parse_hex_u32(pattern[i + 2..i + 10]) or { return false, u8(0), i + 10 }
		if value <= 0xff {
			return true, u8(value), i + 10
		}
		return false, u8(0), i + 10
	}
	return true, next, i + 2
}

fn empty_byte_class() []bool {
	return []bool{len: 256}
}

fn full_byte_class() []bool {
	return []bool{len: 256, init: true}
}

fn invert_byte_class(mut set []bool) {
	for i in 0 .. set.len {
		set[i] = !set[i]
	}
}

fn add_byte_class(mut set []bool, other []bool) {
	for i, present in other {
		if present {
			set[i] = true
		}
	}
}

fn add_byte_range(mut set []bool, start u8, end u8) {
	if start <= end {
		for byte := start; byte <= end; byte++ {
			set[int(byte)] = true
		}
		return
	}
	for byte := end; byte <= start; byte++ {
		set[int(byte)] = true
	}
}

fn add_word_bytes(mut set []bool) {
	add_byte_range(mut set, `A`, `Z`)
	add_byte_range(mut set, `a`, `z`)
	add_byte_range(mut set, `0`, `9`)
	set[int(`_`)] = true
}

fn strip_line_terminator_from_match(pattern string, line_term matcher.LineTerminator) !string {
	mut out := []u8{cap: pattern.len}
	mut i := 0
	mut in_class := false
	for i < pattern.len {
		byte := pattern[i]
		if byte == `[` {
			class, next := strip_class_line_terminator(pattern, i, line_term)!
			out << class.bytes()
			i = next
			continue
		}
		if byte == `]` {
			in_class = false
			out << byte
			i++
			continue
		}
		if byte == `\\` && i + 1 < pattern.len {
			next := pattern[i + 1]
			if next == `s` {
				if line_term.is_crlf() {
					out << '[ \\t\\v\\f]'.bytes()
				} else if line_term.as_byte() == `\n` {
					out << '[ \\t\\r\\v\\f]'.bytes()
				} else {
					out << `\\`
					out << next
				}
				i += 2
				continue
			}
			has_byte, escaped, next_i := parse_escape_byte(pattern, i)
			if has_byte {
				if line_term_rejects_byte(line_term, escaped) {
					return Error.new(ErrorKind.not_allowed([escaped].bytestr()))
				}
			}
			for j in i .. next_i {
				out << pattern[j]
			}
			i = next_i
			continue
		}
		if !in_class && line_term_rejects_byte(line_term, byte) {
			return Error.new(ErrorKind.not_allowed([byte].bytestr()))
		}
		out << byte
		i++
	}
	return out.bytestr()
}

fn strip_class_line_terminator(pattern string, start int, line_term matcher.LineTerminator) !(string, int) {
	mut out := []u8{cap: pattern.len - start}
	out << `[`
	mut i := start + 1
	mut negated := false
	if i < pattern.len && pattern[i] == `^` {
		negated = true
		out << `^`
		i++
	}
	mut kept := 0
	mut excluded_line_term := false
	for i < pattern.len {
		if pattern[i] == `]` {
			if negated {
				if line_term.is_crlf() {
					if !excluded_line_term {
						out << `\\`
						out << `r`
						out << `\\`
						out << `n`
					}
				} else if !excluded_line_term {
					append_escaped_byte(mut out, line_term.as_byte())
				}
			} else if kept == 0 {
				return Error.new(ErrorKind.not_allowed(line_term.as_bytes().bytestr()))
			}
			out << `]`
			return out.bytestr(), i + 1
		}
		if pattern[i] == `\\` && i + 1 < pattern.len {
			next := pattern[i + 1]
			if next == `s` {
				if line_term.is_crlf() {
					out << ' \\t\\v\\f'.bytes()
				} else if line_term.as_byte() == `\n` {
					out << ' \\t\\r\\v\\f'.bytes()
				} else {
					out << `\\`
					out << next
				}
				kept++
				i += 2
				continue
			}
			if is_byte_escape_start(next) {
				has_byte, escaped, next_i := parse_escape_byte(pattern, i)
				if has_byte && line_term_rejects_byte(line_term, escaped) {
					excluded_line_term = true
					i = next_i
					continue
				}
				for j in i .. next_i {
					out << pattern[j]
				}
				kept++
				i = next_i
				continue
			}
			if escaped := escaped_byte(next) {
				if line_term_rejects_byte(line_term, escaped) {
					excluded_line_term = true
					i += 2
					continue
				}
			}
			out << pattern[i]
			out << next
			kept++
			i += 2
			continue
		}
		if line_term_rejects_byte(line_term, pattern[i]) {
			excluded_line_term = true
			i++
			continue
		}
		out << pattern[i]
		kept++
		i++
	}
	return Error.new(ErrorKind.not_allowed(line_term.as_bytes().bytestr()))
}

fn is_byte_escape_start(byte u8) bool {
	return byte == `x` || byte == `u` || byte == `U`
}

fn append_escaped_byte(mut out []u8, byte u8) {
	match byte {
		`\n` {
			out << `\\`
			out << `n`
		}
		`\r` {
			out << `\\`
			out << `r`
		}
		`\t` {
			out << `\\`
			out << `t`
		}
		else {
			out << byte
		}
	}
}

fn escaped_byte(byte u8) ?u8 {
	return match byte {
		`n` { u8(`\n`) }
		`r` { u8(`\r`) }
		`t` { u8(`\t`) }
		else { none }
	}
}

fn line_term_rejects_byte(line_term matcher.LineTerminator, byte u8) bool {
	if line_term.is_crlf() {
		return byte == `\r` || byte == `\n`
	}
	return byte == line_term.as_byte()
}
