module regex

import matcher
import regex.meta

/// Config represents the configuration of a regex matcher in this crate.
/// The configuration is itself a rough combination of the knobs found in
/// the `regex` crate itself, along with additional `grep-matcher` specific
/// options.
///
/// The configuration can be used to build a "configured" HIR expression. A
/// configured HIR expression is an HIR expression that is aware of the
/// configuration which generated it, and provides transformation on that HIR
/// such that the configuration is preserved.
pub struct Config implements IClone {
pub mut:
	case_insensitive     bool
	case_smart           bool
	multi_line           bool
	dot_matches_new_line bool
	swap_greed           bool
	ignore_whitespace    bool
	unicode              bool
	octal                bool
	size_limit           usize
	dfa_size_limit       usize
	nest_limit           u32
	line_terminator      ?matcher.LineTerminator
	ban                  ?u8
	crlf                 bool
	word                 bool
	fixed_strings        bool
	whole_line           bool
}

pub fn Config.default() Config {
	return Config{
		unicode:        true
		size_limit:     usize(100 * (1 << 20))
		dfa_size_limit: usize(1000 * (1 << 20))
		nest_limit:     u32(250)
		line_terminator: none
		ban:             none
	}
}

// V-specific: keep an explicit clone while V2 mark-used/codegen can resolve
// generated clone helpers for same-named structs across modules inconsistently.
pub fn (config Config) clone() Config {
	return Config{
		case_insensitive:     config.case_insensitive
		case_smart:           config.case_smart
		multi_line:           config.multi_line
		dot_matches_new_line: config.dot_matches_new_line
		swap_greed:           config.swap_greed
		ignore_whitespace:    config.ignore_whitespace
		unicode:              config.unicode
		octal:                config.octal
		size_limit:           config.size_limit
		dfa_size_limit:       config.dfa_size_limit
		nest_limit:           config.nest_limit
		line_terminator:      config.line_terminator
		ban:                  config.ban
		crlf:                 config.crlf
		word:                 config.word
		fixed_strings:        config.fixed_strings
		whole_line:           config.whole_line
	}
}

/// Use this configuration to build an HIR from the given patterns. The HIR
/// returned corresponds to a single regex that is an alternation of the
/// patterns given.
pub fn (config Config) build_many(patterns []string) !ConfiguredHIR {
	return ConfiguredHIR.new(config.clone(), patterns)
}

/// Accounting for the `smart_case` config knob, return true if and only if
/// this pattern should be matched case insensitively.
fn (config Config) is_case_insensitive(analysis AstAnalysis) bool {
	if config.case_insensitive {
		return true
	}
	if !config.case_smart {
		return false
	}
	return analysis.any_literal() && !analysis.any_uppercase()
}

/// Returns whether the given patterns should be treated as "fixed strings"
/// literals. This is different from just querying the `fixed_strings` knob
/// in that if the knob is false, this will still return true in some cases
/// if the patterns are themselves indistinguishable from literals.
///
/// The main idea here is that if this returns true, then it is safe
/// to build an `regex_syntax::hir::Hir` value directly from the given
/// patterns as an alternation of `hir::Literal` values.
fn (config Config) is_fixed_strings(patterns []string) bool {
	// When these are enabled, we really need to parse the patterns and
	// let them go through the standard HIR translation process in order
	// for case folding transforms to be applied.
	if config.case_insensitive || config.case_smart {
		return false
	}
	// Even if whole_line or word is enabled, both of those things can
	// be implemented by wrapping the Hir generated by an alternation of
	// fixed string literals. So for here at least, we don't care about the
	// word or whole_line settings.
	if config.fixed_strings {
		// ... but if any literal contains a line terminator, then we've
		// got to bail out because this will ultimately result in an error.
		if lineterm := config.line_terminator {
			for p in patterns {
				if has_line_terminator(lineterm, p) {
					return false
				}
			}
		}
		return true
	}
	// In this case, the only way we can hand construct the Hir is if none
	// of the patterns contain meta characters. If they do, then we need to
	// send them through the standard parsing/translation process.
	for p in patterns {
		for ch in p {
			if is_regex_meta_character(ch) {
				return false
			}
		}
		// Same deal as when fixed_strings is set above. If the pattern has
		// a line terminator anywhere, then we need to bail out and let
		// an error occur.
		if lineterm := config.line_terminator {
			if has_line_terminator(lineterm, p) {
				return false
			}
		}
	}
	return true
}

/// A "configured" HIR expression, which is aware of the configuration which
/// produced this HIR.
///
/// Since the configuration is tracked, values with this type can be
/// transformed into other HIR expressions (or regular expressions) in a way
/// that preserves the configuration. For example, the `fast_line_regex`
/// method will apply literal extraction to the inner HIR and use that to build
/// a new regex that matches the extracted literals in a way that is
/// consistent with the configuration that produced this HIR. For example, the
/// size limits set on the configured HIR will be propagated out to any
/// subsequently constructed HIR or regular expression.
pub struct ConfiguredHIR implements IClone {
	config Config
	hir    Hir
}

/// Parse the given patterns into a single HIR expression that represents
/// an alternation of the patterns given.
fn ConfiguredHIR.new(config Config, patterns []string) !ConfiguredHIR {
	mut hir := Hir.empty()
	if config.is_fixed_strings(patterns) {
		hir = Hir.from_fixed_literals(patterns)
	} else {
		mut alts := []string{cap: patterns.len}
		for p in patterns {
			if config.fixed_strings {
				alts << '(?:${escape_regex(p)})'
			} else {
				validate_rust_regex_syntax(p, config)!
				alts << '(?:${p})'
			}
		}
		mut pattern := if alts.len == 0 { '' } else { alts.join('|') }
		if config.ignore_whitespace {
			pattern = strip_ignored_whitespace(pattern)
		}
		hir = Hir.from_pattern(pattern, config)
	}
	if banned := config.ban {
		ban_check(hir.to_regex(), banned)!
	}
	if line_term := config.line_terminator {
		stripped := strip_line_terminator_from_match(hir.to_regex(), config)!
		hir = Hir.from_pattern(stripped, config)
	}
	return ConfiguredHIR{
		config: config
		hir:    hir
	}
}

/// Return a reference to the underlying configuration.
pub fn (chir &^a ConfiguredHIR) config[^a]() &^a Config {
	return &chir.config
}

/// Return a reference to the underlying HIR.
pub fn (chir &^a ConfiguredHIR) hir[^a]() &^a Hir {
	return &chir.hir
}

/// Convert this HIR to a regex that can be used for matching.
pub fn (chir ConfiguredHIR) to_regex() !meta.Regex {
	pattern := chir.backend_pattern()
	return meta.compile_with_limits(pattern, chir.config.size_limit, chir.config.dfa_size_limit) or {
		return Error.regex(err.msg())
	}
}

/// Compute the set of non-matching bytes for this HIR expression.
pub fn (chir ConfiguredHIR) non_matching_bytes() matcher.ByteSet {
	return chir.hir.non_matching_bytes()
}

/// Returns the line terminator configured on this expression.
///
/// When we have beginning/end anchors (NOT line anchors), the fast line
/// searching path isn't quite correct. Or at least, doesn't match the slow
/// path. Namely, the slow path strips line terminators while the fast path
/// does not. Since '$' (when multi-line mode is disabled) doesn't match at
/// line boundaries, the existence of a line terminator might cause it to
/// not match when it otherwise would with the line terminator stripped.
///
/// Since searching with text anchors is exceptionally rare in the context
/// of line oriented searching (multi-line mode is basically always
/// enabled), we just disable this optimization when there are text
/// anchors. We disable it by not returning a line terminator, since
/// without a line terminator, the fast search path can't be executed.
///
/// Actually, the above is no longer quite correct. Later on, another
/// optimization was added where if the line terminator was in the set of
/// bytes that was guaranteed to never be part of a match, then the higher
/// level search infrastructure assumes that the fast line-by-line search
/// path can still be taken. This optimization applies when multi-line
/// search (not multi-line mode) is enabled. In that case, there is no
/// configured line terminator since the regex is permitted to match a
/// line terminator. But if the regex is guaranteed to never match across
/// multiple lines despite multi-line search being requested, we can still
/// do the faster and more flexible line-by-line search. This is why the
/// non-matching extraction routine removes `\n` when `\A` and `\z` are
/// present even though that's not quite correct...
///
/// See: <https://github.com/BurntSushi/ripgrep/issues/2260>
pub fn (chir ConfiguredHIR) line_terminator() ?matcher.LineTerminator {
	if chir.hir.contains_haystack_anchor() {
		return none
	}
	return chir.config.line_terminator
}

/// Turns this configured HIR into an equivalent one, but where it must
/// match at the start and end of a line.
pub fn (chir ConfiguredHIR) into_whole_line() ConfiguredHIR {
	return ConfiguredHIR{
		config: chir.config.clone()
		hir:    chir.hir.into_whole_line(chir.config)
	}
}

/// Turns this configured HIR into an equivalent one, but where it must
/// match at word boundaries.
pub fn (chir ConfiguredHIR) into_word() ConfiguredHIR {
	return ConfiguredHIR{
		config: chir.config.clone()
		hir:    chir.hir.into_word(chir.config)
	}
}

fn (chir ConfiguredHIR) backend_pattern() string {
	mut flags := ''
	has_haystack_anchor := chir.hir.contains_haystack_anchor()
	pattern := normalize_backend_pattern(chir.hir.to_regex(), chir.config, has_haystack_anchor)
	analysis := AstAnalysis.from_pattern(pattern) or { AstAnalysis.new() }
	if chir.config.is_case_insensitive(analysis) {
		flags += if chir.config.unicode { 'i' } else { 'a' }
	}
	if (chir.config.multi_line || chir.config.crlf) && !has_haystack_anchor {
		flags += 'm'
	}
	if chir.config.dot_matches_new_line {
		flags += 's'
	}
	if !chir.config.unicode {
		flags += '-u'
	}
	if flags.len == 0 {
		return pattern
	}
	return '(?${flags})${pattern}'
}

struct InlineFlags {
	enabled  string
	disabled string
	next     int
	scoped   bool
}

fn inline_flags_at(pattern string, start int) ?InlineFlags {
	if start + 3 >= pattern.len || pattern[start] != `(` || pattern[start + 1] != `?` {
		return none
	}
	mut i := start + 2
	mut enabled := []u8{}
	mut disabled := []u8{}
	mut disabling := false
	mut saw_flag := false
	for i < pattern.len && pattern[i] !in [`:`, `)`] {
		if pattern[i] == `-` {
			if disabling {
				return none
			}
			disabling = true
			i++
			continue
		}
		if pattern[i] !in [`i`, `m`, `s`, `U`, `u`, `x`, `R`] {
			return none
		}
		saw_flag = true
		if disabling {
			disabled << pattern[i]
		} else {
			enabled << pattern[i]
		}
		i++
	}
	if !saw_flag || i >= pattern.len {
		return none
	}
	return InlineFlags{
		enabled:  enabled.bytestr()
		disabled: disabled.bytestr()
		next:     i + 1
		scoped:   pattern[i] == `:`
	}
}

fn apply_inline_flags(flags InlineFlags, config Config) Config {
	mut next := config
	for flag in flags.enabled.bytes() {
		match flag {
			`U` { next.swap_greed = true }
			`u` { next.unicode = true }
			`x` { next.ignore_whitespace = true }
			`R` { next.crlf = true }
			else {}
		}
	}
	for flag in flags.disabled.bytes() {
		match flag {
			`U` { next.swap_greed = false }
			`u` { next.unicode = false }
			`x` { next.ignore_whitespace = false }
			`R` { next.crlf = false }
			else {}
		}
	}
	return next
}

fn backend_inline_flags(flags InlineFlags, unicode bool) string {
	mut enabled := []u8{}
	mut disabled := []u8{}
	for flag in flags.enabled.bytes() {
		match flag {
			`i` { enabled << if unicode { `i` } else { `a` } }
			`m`, `s`, `u` { enabled << flag }
			else {}
		}
	}
	for flag in flags.disabled.bytes() {
		match flag {
			`i` { disabled << `i` }
			`m`, `s`, `u` { disabled << flag }
			else {}
		}
	}
	mut out := enabled.bytestr()
	if disabled.len > 0 {
		out += '-${disabled.bytestr()}'
	}
	return out
}

fn normalize_backend_pattern(pattern string, config Config, explicit_line_anchors bool) string {
	mut out := []u8{cap: pattern.len}
	mut i := 0
	mut in_class := false
	mut escaped := false
	mut effective_config := config
	for i < pattern.len {
		ch := pattern[i]
		if !escaped && !in_class {
			if flags := inline_flags_at(pattern, i) {
				next_config := apply_inline_flags(flags, effective_config)
				backend_flags := backend_inline_flags(flags, next_config.unicode)
				if flags.scoped {
					if end := matching_group_end(pattern, i) {
						out << if backend_flags == '' { '(?:'.bytes() } else { '(?${backend_flags}:'.bytes() }
						out << normalize_backend_pattern(pattern[flags.next..int(end)], next_config,
							explicit_line_anchors).bytes()
						out << `)`
						i = int(end) + 1
						escaped = false
						continue
					}
				} else {
					effective_config = next_config
					if backend_flags != '' {
						out << '(?${backend_flags})'.bytes()
					}
					i = flags.next
					escaped = false
					continue
				}
			}
		}
		if !escaped && !in_class && ch == `[` {
			if replacement := normalize_unicode_class_at(pattern, i, effective_config) {
				out << replacement.text.bytes()
				i = replacement.next
				escaped = false
				continue
			}
			if replacement := normalize_posix_alpha_class_at(pattern, i, effective_config) {
				out << replacement.text.bytes()
				i = replacement.next
				escaped = false
				continue
			}
			if replacement := normalize_class_set_operation_at(pattern, i, effective_config) {
				out << replacement.text.bytes()
				i = replacement.next
				escaped = false
				continue
			}
			if replacement := normalize_property_class_at(pattern, i, effective_config) {
				out << replacement.text.bytes()
				i = replacement.next
				escaped = false
				continue
			}
		}
		if effective_config.ignore_whitespace && !escaped && !in_class && ch == `#` {
			for i < pattern.len && pattern[i] != `\n` {
				i++
			}
			escaped = false
			continue
		}
		if effective_config.ignore_whitespace && !escaped && !in_class && is_extended_whitespace(ch) {
			i++
			escaped = false
			continue
		}
		if explicit_line_anchors && (effective_config.multi_line || effective_config.crlf) && !escaped && !in_class
			&& ch == `^` {
			out << r'(?m:^)'.bytes()
			i++
			escaped = false
			continue
		}
		if explicit_line_anchors && (effective_config.multi_line || effective_config.crlf) && !escaped && !in_class
			&& ch == `$` {
			if effective_config.crlf {
				out << r'\x0D?(?m:$)'.bytes()
			} else {
				out << r'(?m:$)'.bytes()
			}
			i++
			escaped = false
			continue
		}
		if effective_config.crlf && !escaped && !in_class && ch == `$` {
			out << r'\x0D?$'.bytes()
			i++
			continue
		}
		if !escaped && !in_class && i + 3 < pattern.len && ch == `(` && pattern[i + 1] == `?`
			&& pattern[i + 2] == `<` && pattern[i + 3] != `=` && pattern[i + 3] != `!` {
			out << '(?P<'.bytes()
			i += 3
			escaped = false
			continue
		}
		if !escaped && ch == `[` {
			in_class = true
		} else if !escaped && ch == `]` {
			in_class = false
		}
		if !escaped && !in_class && ch == `\\` {
			if variant := rust_word_boundary_variant_at(pattern, i) {
				out << backend_word_boundary(variant.kind, effective_config.unicode).bytes()
				i = variant.next
				escaped = false
				continue
			}
			if i + 1 < pattern.len {
				next := pattern[i + 1]
				match next {
					`A` {
						out << r'\A'.bytes()
						i += 2
						escaped = false
						continue
					}
					`z` {
						out << r'\z'.bytes()
						i += 2
						escaped = false
						continue
					}
					`<`, `>` {
						kind := if next == `<` { 'start' } else { 'end' }
						out << backend_word_boundary(kind, effective_config.unicode).bytes()
						i += 2
						escaped = false
						continue
					}
					`b`, `B` {
						kind := if next == `b` { 'boundary' } else { 'negate' }
						out << backend_word_boundary(kind, effective_config.unicode).bytes()
						i += 2
						escaped = false
						continue
					}
					`x`, `u`, `U` {
						if escape := rust_unicode_escape_at(pattern, i) {
							if escape.codepoint <= 0xff {
								out << '\\x${escape.codepoint:02x}'.bytes()
							} else {
								out << rune(escape.codepoint).str().bytes()
							}
							i = escape.next
							escaped = false
							continue
						}
					}
					`d` {
						out << digit_backend_class(effective_config).bytes()
						i += 2
						escaped = false
						continue
					}
					`D` {
						out << negated_backend_class(digit_backend_class_body(effective_config),
							effective_config).bytes()
						i += 2
						escaped = false
						continue
					}
					`s` {
						out << whitespace_backend_class(effective_config).bytes()
						i += 2
						escaped = false
						continue
					}
					`S` {
						out << negated_backend_class(whitespace_backend_class_body(effective_config),
							effective_config).bytes()
						i += 2
						escaped = false
						continue
					}
					`w` {
						out << word_backend_class(effective_config).bytes()
						i += 2
						escaped = false
						continue
					}
					`W` {
						out << negated_backend_class(word_backend_class_body(effective_config),
							effective_config).bytes()
						i += 2
						escaped = false
						continue
					}
					`p`, `P` {
						if property_escape := rust_property_escape_at(pattern, i) {
							if next == `p` {
								if replacement := rust_property_replacement(property_escape.property,
									effective_config) {
									out << replacement.bytes()
									i = property_escape.next
									escaped = false
									continue
								}
							} else {
								if normalize_property_name(property_escape.property) == 'any' {
									out << r'(?:a^)'.bytes()
									i = property_escape.next
									escaped = false
									continue
								}
								if body := rust_property_class_body(property_escape.property,
									effective_config) {
									out << negated_backend_class(body, effective_config).bytes()
									i = property_escape.next
									escaped = false
									continue
								}
							}
						}
					}
					else {}
				}
			}
		}
		if !escaped && !in_class && effective_config.swap_greed
			&& is_standalone_single_quantifier(pattern, i) {
			out << ch
			if i + 1 < pattern.len && pattern[i + 1] in [`?`, `+`] {
				if pattern[i + 1] == `+` {
					out << `?`
				}
				i += 2
			} else {
				out << `?`
				i++
			}
			escaped = false
			continue
		}
		if !escaped && !in_class && is_possessive_single_quantifier(pattern, i) {
			out << ch
			i += 2
			escaped = false
			continue
		}
		if !escaped && !in_class && ch == `{` {
			if effective_config.swap_greed {
				if end := braced_quantifier_end(pattern, i) {
					out << pattern[i..int(end) + 1].bytes()
					if int(end) + 1 < pattern.len && pattern[int(end) + 1] in [`?`, `+`] {
						if pattern[int(end) + 1] == `+` {
							out << `?`
						}
						i = int(end) + 2
					} else {
						out << `?`
						i = int(end) + 1
					}
					escaped = false
					continue
				}
			}
			if end := possessive_braced_quantifier_end(pattern, i) {
				out << pattern[i..int(end) + 1].bytes()
				i = int(end) + 2
				escaped = false
				continue
			}
		}
		out << ch
		escaped = !escaped && ch == `\\`
		i++
	}
	return out.bytestr()
}

struct RustBracedHexEscape {
	codepoint u32
	next      int
}

fn rust_braced_hex_escape_at(pattern string, i int) ?RustBracedHexEscape {
	if i + 3 >= pattern.len || pattern[i..i + 3] != r'\x{' {
		return none
	}
	mut end := i + 3
	for end < pattern.len && pattern[end] != `}` {
		end++
	}
	if end >= pattern.len || end == i + 3 {
		return none
	}
	codepoint := parse_hex_u32(pattern[i + 3..end]) or { return none }
	if codepoint > 0x10ffff || (codepoint >= 0xd800 && codepoint <= 0xdfff) {
		return none
	}
	return RustBracedHexEscape{
		codepoint: codepoint
		next:      end + 1
	}
}

fn rust_unicode_escape_at(pattern string, i int) ?RustBracedHexEscape {
	if escape := rust_braced_hex_escape_at(pattern, i) {
		return escape
	}
	if i + 2 >= pattern.len || pattern[i] != `\\` || pattern[i + 1] !in [`u`, `U`] {
		return none
	}
	if pattern[i + 1] == `u` && pattern[i + 2] == `{` {
		mut end := i + 3
		for end < pattern.len && pattern[end] != `}` {
			end++
		}
		if end >= pattern.len || end == i + 3 {
			return none
		}
		codepoint := parse_hex_u32(pattern[i + 3..end]) or { return none }
		if !is_valid_unicode_escape_codepoint(codepoint) {
			return none
		}
		return RustBracedHexEscape{
			codepoint: codepoint
			next:      end + 1
		}
	}
	digits := if pattern[i + 1] == `u` { 4 } else { 8 }
	if i + 2 + digits > pattern.len {
		return none
	}
	codepoint := parse_hex_u32(pattern[i + 2..i + 2 + digits]) or { return none }
	if !is_valid_unicode_escape_codepoint(codepoint) {
		return none
	}
	return RustBracedHexEscape{
		codepoint: codepoint
		next:      i + 2 + digits
	}
}

fn is_valid_unicode_escape_codepoint(codepoint u32) bool {
	return codepoint <= 0x10ffff && !(codepoint >= 0xd800 && codepoint <= 0xdfff)
}

fn matching_group_end(pattern string, start int) ?usize {
	mut depth := 0
	mut escaped := false
	mut in_class := false
	for i := start; i < pattern.len; i++ {
		ch := pattern[i]
		if escaped {
			escaped = false
			continue
		}
		if ch == `\\` {
			escaped = true
			continue
		}
		if in_class {
			if ch == `]` {
				in_class = false
			}
			continue
		}
		if ch == `[` {
			in_class = true
			continue
		}
		if ch == `(` {
			depth++
			continue
		}
		if ch == `)` {
			depth--
			if depth == 0 {
				return usize(i)
			}
		}
	}
	return none
}

struct RustWordBoundaryVariant {
	kind string
	next int
}

fn rust_word_boundary_variant_at(pattern string, i int) ?RustWordBoundaryVariant {
	variants := {
		r'\b{start}':      'start'
		r'\b{end}':        'end'
		r'\b{start-half}': 'start-half'
		r'\b{end-half}':   'end-half'
	}
	for variant, kind in variants {
		if i + variant.len <= pattern.len && pattern[i..i + variant.len] == variant {
			return RustWordBoundaryVariant{
				kind: kind.to_owned()
				next: i + variant.len
			}
		}
	}
	return none
}

fn backend_word_boundary(kind string, unicode bool) string {
	mode := if unicode { 'unicode' } else { 'ascii' }
	return '\\b{${kind}-${mode}}'
}

fn rust_property_escape_end(pattern string, i int) ?usize {
	if i + 3 >= pattern.len || pattern[i] != `\\` || (pattern[i + 1] != `p`
		&& pattern[i + 1] != `P`) || pattern[i + 2] != `{` {
		return none
	}
	mut end := i + 3
	for end < pattern.len && pattern[end] != `}` {
		end++
	}
	if end >= pattern.len {
		return none
	}
	return usize(end + 1)
}

struct RustPropertyEscape {
	property string
	next     int
}

fn rust_property_escape_at(pattern string, i int) ?RustPropertyEscape {
	if i + 2 >= pattern.len || pattern[i] != `\\` || (pattern[i + 1] != `p`
		&& pattern[i + 1] != `P`) {
		return none
	}
	if end := rust_property_escape_end(pattern, i) {
		return RustPropertyEscape{
			property: pattern[i + 3..int(end) - 1].to_owned()
			next:     int(end)
		}
	}
	next := pattern[i + 2]
	if is_ascii_property_letter(next) {
		return RustPropertyEscape{
			property: next.ascii_str().to_owned()
			next:     i + 3
		}
	}
	return none
}

fn is_ascii_property_letter(byte u8) bool {
	return (byte >= `A` && byte <= `Z`) || (byte >= `a` && byte <= `z`)
}

fn rust_property_replacement(property string, config Config) ?string {
	normalized := normalize_property_name(property)
	if normalized == 'any' {
		return '(?:.|\n|\r)'
	}
	if normalized == 'ascii' {
		return ascii_backend_class()
	}
	if body := rust_property_class_body(property, config) {
		return '[${body}]'
	}
	return none
}

fn rust_property_class_body(property string, config Config) ?string {
	encoded := rust_property_class_encoded(property, config) or { return none }
	return generated_unicode_range_body(encoded)
}

fn rust_property_class_encoded(property string, config Config) ?string {
	_ = config
	normalized := normalize_property_name(property)
	if key := generated_unicode_binary_property_key(normalized) {
		return generated_unicode_property_encoded(key)
	}
	if !normalized.contains('=') {
		return none
	}
	property_name := normalized.all_before('=')
	property_value := normalized.all_after('=')
	canonical_property := generated_unicode_property_name(property_name) or { return none }
	canonical_value := generated_unicode_property_value(canonical_property, property_value) or {
		return none
	}
	table := match canonical_property {
		'Age' { 'age' }
		'General_Category' { 'gc' }
		'Script' { 'script' }
		'Script_Extensions' { 'scx' }
		'Grapheme_Cluster_Break' { 'gcb' }
		'Sentence_Break' { 'sb' }
		'Word_Break' { 'wb' }
		else { return none }
	}
	return generated_unicode_property_encoded('${table}=${canonical_value}')
}

fn normalize_property_name(property string) string {
	mut out := []u8{cap: property.len}
	for byte in property.to_lower().bytes() {
		if byte == `_` || byte == `-` || byte == ` ` {
			continue
		}
		if byte == `:` {
			out << `=`
			continue
		}
		out << byte
	}
	return out.bytestr()
}

fn rust_property_is_supported(property string, config Config) bool {
	normalized := normalize_property_name(property)
	if normalized == 'any' {
		return true
	}
	return rust_property_class_body(property, config) != none
}

fn word_backend_class(config Config) string {
	return '[${word_backend_class_body(config)}]'
}

fn word_backend_class_body(config Config) string {
	if config.unicode {
		return generated_unicode_word_body()
	}
	return 'A-Za-z0-9_'
}

fn letter_backend_class() string {
	return '[${letter_backend_class_body()}]'
}

fn letter_backend_class_body() string {
	return ranges_backend_class_body(letter_ranges())
}

fn uppercase_letter_backend_class_body() string {
	return ranges_backend_class_body(uppercase_letter_ranges())
}

fn digit_backend_class(config Config) string {
	return '[${digit_backend_class_body(config)}]'
}

fn digit_backend_class_body(config Config) string {
	if config.unicode {
		return decimal_digit_backend_class_body(config)
	}
	return '0-9'
}

fn decimal_digit_backend_class_body(config Config) string {
	_ = config
	return ranges_backend_class_body(decimal_digit_ranges())
}

fn whitespace_backend_class(config Config) string {
	return '[${whitespace_backend_class_body(config)}]'
}

fn whitespace_backend_class_body(config Config) string {
	if !config.unicode {
		return ascii_whitespace_backend_class_body()
	}
	return ranges_backend_class_body(whitespace_ranges())
}

fn ascii_whitespace_backend_class_body() string {
	return ranges_backend_class_body([
		UnicodeRange{`\t`, `\r`},
		UnicodeRange{` `, ` `},
	])
}

fn ascii_backend_class() string {
	return '[${ascii_backend_class_body()}]'
}

fn ascii_backend_class_body() string {
	return ranges_backend_class_body([
		UnicodeRange{rune(0), rune(0x7f)},
	])
}

struct UnicodeRange {
	start rune
	end   rune
}

fn unicode_ranges_from_encoded(encoded string) []UnicodeRange {
	mut ranges := []UnicodeRange{cap: encoded.count(',') + 1}
	for encoded_range in encoded.split(',') {
		if encoded_range.len == 0 {
			continue
		}
		if encoded_range.contains('-') {
			ranges << UnicodeRange{
				start: rune(parse_generated_unicode_hex(encoded_range.all_before('-')))
				end:   rune(parse_generated_unicode_hex(encoded_range.all_after('-')))
			}
		} else {
			value := rune(parse_generated_unicode_hex(encoded_range))
			ranges << UnicodeRange{value, value}
		}
	}
	return ranges
}

fn union_unicode_ranges(left []UnicodeRange, right []UnicodeRange) []UnicodeRange {
	mut all := []UnicodeRange{cap: left.len + right.len}
	all << left
	all << right
	all.sort(a.start < b.start || (a.start == b.start && a.end < b.end))
	mut out := []UnicodeRange{cap: all.len}
	for current in all {
		if out.len == 0 || current.start > out.last().end + 1 {
			out << current
		} else if current.end > out.last().end {
			out[out.len - 1].end = current.end
		}
	}
	return out
}

fn intersect_unicode_ranges(left []UnicodeRange, right []UnicodeRange) []UnicodeRange {
	mut out := []UnicodeRange{}
	mut i := 0
	mut j := 0
	for i < left.len && j < right.len {
		start := if left[i].start > right[j].start { left[i].start } else { right[j].start }
		end := if left[i].end < right[j].end { left[i].end } else { right[j].end }
		if start <= end {
			out << UnicodeRange{start, end}
		}
		if left[i].end < right[j].end {
			i++
		} else {
			j++
		}
	}
	return out
}

fn subtract_unicode_ranges(left []UnicodeRange, right []UnicodeRange) []UnicodeRange {
	mut out := []UnicodeRange{}
	mut right_index := 0
	for source in left {
		mut cursor := source.start
		for right_index < right.len && right[right_index].end < cursor {
			right_index++
		}
		mut j := right_index
		for j < right.len && right[j].start <= source.end {
			if right[j].start > cursor {
				out << UnicodeRange{cursor, right[j].start - 1}
			}
			if right[j].end >= source.end {
				cursor = source.end + 1
				break
			}
			if right[j].end >= cursor {
				cursor = right[j].end + 1
			}
			j++
		}
		if cursor <= source.end {
			out << UnicodeRange{cursor, source.end}
		}
	}
	return out
}

fn complement_unicode_ranges(ranges []UnicodeRange) []UnicodeRange {
	return subtract_unicode_ranges([UnicodeRange{rune(0), rune(0x10ffff)}], ranges)
}

fn symmetric_difference_unicode_ranges(left []UnicodeRange, right []UnicodeRange) []UnicodeRange {
	return union_unicode_ranges(subtract_unicode_ranges(left, right), subtract_unicode_ranges(right,
		left))
}

fn ranges_backend_class_body(ranges []UnicodeRange) string {
	mut out := []u8{cap: ranges.len * 8}
	for range_ in ranges {
		append_backend_class_rune(mut out, range_.start)
		if range_.end != range_.start {
			out << `-`
			append_backend_class_rune(mut out, range_.end)
		}
	}
	return out.bytestr()
}

fn generated_unicode_range_body(encoded string) string {
	mut out := []u8{cap: encoded.len}
	for encoded_range in encoded.split(',') {
		if encoded_range.len == 0 {
			continue
		}
		if encoded_range.contains('-') {
			append_backend_class_rune(mut out, rune(parse_generated_unicode_hex(encoded_range.all_before('-'))))
			out << `-`
			append_backend_class_rune(mut out, rune(parse_generated_unicode_hex(encoded_range.all_after('-'))))
		} else {
			append_backend_class_rune(mut out, rune(parse_generated_unicode_hex(encoded_range)))
		}
	}
	return out.bytestr()
}

fn parse_generated_unicode_hex(hex string) u32 {
	mut value := u32(0)
	for byte in hex.bytes() {
		value <<= 4
		value |= if byte >= `0` && byte <= `9` {
			u32(byte - `0`)
		} else {
			u32(byte - `a` + 10)
		}
	}
	return value
}

fn append_backend_class_rune(mut out []u8, rn rune) {
	if rn >= 0 && rn <= 0xff
		&& (rn < 0x20 || rn >= 0x7f || rn in [`\\`, `]`, `[`, `-`, `^`]) {
		hex := '0123456789abcdef'
		out << `\\`
		out << `x`
		out << hex[int(rn) >> 4]
		out << hex[int(rn) & 0x0f]
		return
	}
	out << rn.str().bytes()
}

fn latin_ranges() []UnicodeRange {
	return [
		UnicodeRange{`A`, `Z`},
		UnicodeRange{`a`, `z`},
		UnicodeRange{rune(0x00aa), rune(0x00aa)},
		UnicodeRange{rune(0x00b5), rune(0x00b5)},
		UnicodeRange{rune(0x00ba), rune(0x00ba)},
		UnicodeRange{rune(0x00c0), rune(0x00d6)},
		UnicodeRange{rune(0x00d8), rune(0x00f6)},
		UnicodeRange{rune(0x00f8), rune(0x02af)},
		UnicodeRange{rune(0x1d00), rune(0x1d7f)},
		UnicodeRange{rune(0x1d80), rune(0x1dbf)},
		UnicodeRange{rune(0x1e00), rune(0x1eff)},
		UnicodeRange{rune(0x2071), rune(0x2071)},
		UnicodeRange{rune(0x207f), rune(0x207f)},
		UnicodeRange{rune(0x2090), rune(0x209c)},
		UnicodeRange{rune(0x212a), rune(0x212b)},
		UnicodeRange{rune(0x2c60), rune(0x2c7f)},
		UnicodeRange{rune(0xa720), rune(0xa7ff)},
		UnicodeRange{rune(0xab30), rune(0xab6f)},
		UnicodeRange{rune(0xff21), rune(0xff3a)},
		UnicodeRange{rune(0xff41), rune(0xff5a)},
	]
}

fn greek_ranges() []UnicodeRange {
	return [
		UnicodeRange{rune(0x0370), rune(0x03ff)},
		UnicodeRange{rune(0x1f00), rune(0x1fff)},
	]
}

fn cyrillic_ranges() []UnicodeRange {
	return [
		UnicodeRange{rune(0x0400), rune(0x052f)},
		UnicodeRange{rune(0x1c80), rune(0x1c88)},
		UnicodeRange{rune(0x1d2b), rune(0x1d2b)},
		UnicodeRange{rune(0x1d78), rune(0x1d78)},
		UnicodeRange{rune(0x2de0), rune(0x2dff)},
		UnicodeRange{rune(0xa640), rune(0xa69f)},
		UnicodeRange{rune(0xfe2e), rune(0xfe2f)},
	]
}

fn hebrew_ranges() []UnicodeRange {
	return [
		UnicodeRange{rune(0x0590), rune(0x05ff)},
		UnicodeRange{rune(0xfb1d), rune(0xfb4f)},
	]
}

fn arabic_ranges() []UnicodeRange {
	return [
		UnicodeRange{rune(0x0600), rune(0x06ff)},
		UnicodeRange{rune(0x0750), rune(0x077f)},
		UnicodeRange{rune(0x0870), rune(0x089f)},
		UnicodeRange{rune(0x08a0), rune(0x08ff)},
		UnicodeRange{rune(0xfb50), rune(0xfdff)},
		UnicodeRange{rune(0xfe70), rune(0xfeff)},
	]
}

fn han_ranges() []UnicodeRange {
	return [
		UnicodeRange{rune(0x2e80), rune(0x2eff)},
		UnicodeRange{rune(0x2f00), rune(0x2fdf)},
		UnicodeRange{rune(0x3005), rune(0x3007)},
		UnicodeRange{rune(0x3021), rune(0x3029)},
		UnicodeRange{rune(0x3038), rune(0x303b)},
		UnicodeRange{rune(0x3400), rune(0x4dbf)},
		UnicodeRange{rune(0x4e00), rune(0x9fff)},
		UnicodeRange{rune(0xf900), rune(0xfaff)},
		UnicodeRange{rune(0x20000), rune(0x2a6df)},
		UnicodeRange{rune(0x2a700), rune(0x2b73f)},
		UnicodeRange{rune(0x2b740), rune(0x2b81f)},
		UnicodeRange{rune(0x2b820), rune(0x2ceaf)},
		UnicodeRange{rune(0x2ceb0), rune(0x2ebef)},
		UnicodeRange{rune(0x30000), rune(0x3134f)},
	]
}

fn hiragana_ranges() []UnicodeRange {
	return [
		UnicodeRange{rune(0x3040), rune(0x309f)},
		UnicodeRange{rune(0x1b001), rune(0x1b11f)},
	]
}

fn katakana_ranges() []UnicodeRange {
	return [
		UnicodeRange{rune(0x30a0), rune(0x30ff)},
		UnicodeRange{rune(0x31f0), rune(0x31ff)},
		UnicodeRange{rune(0x32d0), rune(0x32fe)},
		UnicodeRange{rune(0x3300), rune(0x3357)},
		UnicodeRange{rune(0xff66), rune(0xff9f)},
		UnicodeRange{rune(0x1b000), rune(0x1b000)},
		UnicodeRange{rune(0x1b120), rune(0x1b12f)},
	]
}

fn decimal_digit_ranges() []UnicodeRange {
	return [
		UnicodeRange{`0`, `9`},
		UnicodeRange{rune(0x0660), rune(0x0669)},
		UnicodeRange{rune(0x06f0), rune(0x06f9)},
		UnicodeRange{rune(0x07c0), rune(0x07c9)},
		UnicodeRange{rune(0x0966), rune(0x096f)},
		UnicodeRange{rune(0x09e6), rune(0x09ef)},
		UnicodeRange{rune(0x0a66), rune(0x0a6f)},
		UnicodeRange{rune(0x0ae6), rune(0x0aef)},
		UnicodeRange{rune(0x0b66), rune(0x0b6f)},
		UnicodeRange{rune(0x0be6), rune(0x0bef)},
		UnicodeRange{rune(0x0c66), rune(0x0c6f)},
		UnicodeRange{rune(0x0ce6), rune(0x0cef)},
		UnicodeRange{rune(0x0d66), rune(0x0d6f)},
		UnicodeRange{rune(0x0de6), rune(0x0def)},
		UnicodeRange{rune(0x0e50), rune(0x0e59)},
		UnicodeRange{rune(0x0ed0), rune(0x0ed9)},
		UnicodeRange{rune(0x0f20), rune(0x0f29)},
		UnicodeRange{rune(0x1040), rune(0x1049)},
		UnicodeRange{rune(0x1090), rune(0x1099)},
		UnicodeRange{rune(0x17e0), rune(0x17e9)},
		UnicodeRange{rune(0x1810), rune(0x1819)},
		UnicodeRange{rune(0x1946), rune(0x194f)},
		UnicodeRange{rune(0x19d0), rune(0x19d9)},
		UnicodeRange{rune(0x1a80), rune(0x1a89)},
		UnicodeRange{rune(0x1a90), rune(0x1a99)},
		UnicodeRange{rune(0x1b50), rune(0x1b59)},
		UnicodeRange{rune(0x1bb0), rune(0x1bb9)},
		UnicodeRange{rune(0x1c40), rune(0x1c49)},
		UnicodeRange{rune(0x1c50), rune(0x1c59)},
		UnicodeRange{rune(0xa620), rune(0xa629)},
		UnicodeRange{rune(0xa8d0), rune(0xa8d9)},
		UnicodeRange{rune(0xa900), rune(0xa909)},
		UnicodeRange{rune(0xa9d0), rune(0xa9d9)},
		UnicodeRange{rune(0xa9f0), rune(0xa9f9)},
		UnicodeRange{rune(0xaa50), rune(0xaa59)},
		UnicodeRange{rune(0xabf0), rune(0xabf9)},
		UnicodeRange{rune(0xff10), rune(0xff19)},
		UnicodeRange{rune(0x104a0), rune(0x104a9)},
		UnicodeRange{rune(0x11066), rune(0x1106f)},
		UnicodeRange{rune(0x110f0), rune(0x110f9)},
		UnicodeRange{rune(0x11136), rune(0x1113f)},
		UnicodeRange{rune(0x111d0), rune(0x111d9)},
		UnicodeRange{rune(0x112f0), rune(0x112f9)},
		UnicodeRange{rune(0x11450), rune(0x11459)},
		UnicodeRange{rune(0x114d0), rune(0x114d9)},
		UnicodeRange{rune(0x11650), rune(0x11659)},
		UnicodeRange{rune(0x116c0), rune(0x116c9)},
		UnicodeRange{rune(0x11730), rune(0x11739)},
		UnicodeRange{rune(0x118e0), rune(0x118e9)},
		UnicodeRange{rune(0x11950), rune(0x11959)},
		UnicodeRange{rune(0x11c50), rune(0x11c59)},
		UnicodeRange{rune(0x11d50), rune(0x11d59)},
		UnicodeRange{rune(0x11da0), rune(0x11da9)},
		UnicodeRange{rune(0x16a60), rune(0x16a69)},
		UnicodeRange{rune(0x16ac0), rune(0x16ac9)},
		UnicodeRange{rune(0x16b50), rune(0x16b59)},
		UnicodeRange{rune(0x1d7ce), rune(0x1d7ff)},
		UnicodeRange{rune(0x1e140), rune(0x1e149)},
		UnicodeRange{rune(0x1e2f0), rune(0x1e2f9)},
		UnicodeRange{rune(0x1e950), rune(0x1e959)},
		UnicodeRange{rune(0x1fbf0), rune(0x1fbf9)},
	]
}

fn whitespace_ranges() []UnicodeRange {
	return [
		UnicodeRange{`\t`, `\r`},
		UnicodeRange{` `, ` `},
		UnicodeRange{rune(0x0085), rune(0x0085)},
		UnicodeRange{rune(0x00a0), rune(0x00a0)},
		UnicodeRange{rune(0x1680), rune(0x1680)},
		UnicodeRange{rune(0x2000), rune(0x200a)},
		UnicodeRange{rune(0x2028), rune(0x2029)},
		UnicodeRange{rune(0x202f), rune(0x202f)},
		UnicodeRange{rune(0x205f), rune(0x205f)},
		UnicodeRange{rune(0x3000), rune(0x3000)},
	]
}

fn letter_ranges() []UnicodeRange {
	mut ranges := []UnicodeRange{}
	ranges << latin_ranges()
	ranges << greek_ranges()
	ranges << cyrillic_ranges()
	ranges << hebrew_ranges()
	ranges << arabic_ranges()
	ranges << han_ranges()
	ranges << hiragana_ranges()
	ranges << katakana_ranges()
	ranges << [
		UnicodeRange{rune(0x0900), rune(0x097f)},
		UnicodeRange{rune(0x0980), rune(0x09ff)},
		UnicodeRange{rune(0x0a00), rune(0x0a7f)},
		UnicodeRange{rune(0x0a80), rune(0x0aff)},
		UnicodeRange{rune(0x0b00), rune(0x0b7f)},
		UnicodeRange{rune(0x0b80), rune(0x0bff)},
		UnicodeRange{rune(0x0c00), rune(0x0c7f)},
		UnicodeRange{rune(0x0c80), rune(0x0cff)},
		UnicodeRange{rune(0x0d00), rune(0x0d7f)},
		UnicodeRange{rune(0x0d80), rune(0x0dff)},
		UnicodeRange{rune(0x0e00), rune(0x0e7f)},
		UnicodeRange{rune(0x0e80), rune(0x0eff)},
		UnicodeRange{rune(0x0f00), rune(0x0fff)},
		UnicodeRange{rune(0x1000), rune(0x109f)},
		UnicodeRange{rune(0x1100), rune(0x11ff)},
		UnicodeRange{rune(0x1200), rune(0x137f)},
		UnicodeRange{rune(0x13a0), rune(0x13ff)},
		UnicodeRange{rune(0x1400), rune(0x167f)},
		UnicodeRange{rune(0x1680), rune(0x169f)},
		UnicodeRange{rune(0x16a0), rune(0x16ff)},
		UnicodeRange{rune(0x1700), rune(0x171f)},
		UnicodeRange{rune(0x1720), rune(0x173f)},
		UnicodeRange{rune(0x1740), rune(0x175f)},
		UnicodeRange{rune(0x1760), rune(0x177f)},
		UnicodeRange{rune(0x1780), rune(0x17ff)},
		UnicodeRange{rune(0x1800), rune(0x18af)},
		UnicodeRange{rune(0x1900), rune(0x194f)},
		UnicodeRange{rune(0x1950), rune(0x197f)},
		UnicodeRange{rune(0x1980), rune(0x19df)},
		UnicodeRange{rune(0x1a00), rune(0x1a7f)},
		UnicodeRange{rune(0x1b00), rune(0x1b7f)},
		UnicodeRange{rune(0x1c00), rune(0x1c7f)},
		UnicodeRange{rune(0x2c00), rune(0x2c5f)},
		UnicodeRange{rune(0x2d00), rune(0x2d2f)},
		UnicodeRange{rune(0x2d30), rune(0x2d7f)},
		UnicodeRange{rune(0xa000), rune(0xa48f)},
		UnicodeRange{rune(0xa4d0), rune(0xa4ff)},
		UnicodeRange{rune(0xa500), rune(0xa63f)},
		UnicodeRange{rune(0xa6a0), rune(0xa6ff)},
		UnicodeRange{rune(0xa800), rune(0xa82f)},
		UnicodeRange{rune(0xa840), rune(0xa87f)},
		UnicodeRange{rune(0xa880), rune(0xa8df)},
		UnicodeRange{rune(0xa900), rune(0xa92f)},
		UnicodeRange{rune(0xa930), rune(0xa95f)},
		UnicodeRange{rune(0xa960), rune(0xa97f)},
		UnicodeRange{rune(0xa980), rune(0xa9df)},
		UnicodeRange{rune(0xaa00), rune(0xaa5f)},
		UnicodeRange{rune(0xaa60), rune(0xaa7f)},
		UnicodeRange{rune(0xaa80), rune(0xaadf)},
		UnicodeRange{rune(0xab00), rune(0xab2f)},
		UnicodeRange{rune(0xab70), rune(0xabbf)},
		UnicodeRange{rune(0xac00), rune(0xd7af)},
		UnicodeRange{rune(0xd7b0), rune(0xd7ff)},
	]
	return ranges
}

fn uppercase_letter_ranges() []UnicodeRange {
	return [
		UnicodeRange{`A`, `Z`},
		UnicodeRange{rune(0x00c0), rune(0x00d6)},
		UnicodeRange{rune(0x00d8), rune(0x00de)},
		UnicodeRange{rune(0x0100), rune(0x0136)},
		UnicodeRange{rune(0x0139), rune(0x0147)},
		UnicodeRange{rune(0x014a), rune(0x0178)},
		UnicodeRange{rune(0x0181), rune(0x0243)},
		UnicodeRange{rune(0x0386), rune(0x0386)},
		UnicodeRange{rune(0x0388), rune(0x038a)},
		UnicodeRange{rune(0x038c), rune(0x038c)},
		UnicodeRange{rune(0x038e), rune(0x03ab)},
		UnicodeRange{rune(0x03cf), rune(0x03cf)},
		UnicodeRange{rune(0x03d2), rune(0x03d4)},
		UnicodeRange{rune(0x03f4), rune(0x03ff)},
		UnicodeRange{rune(0x0400), rune(0x042f)},
		UnicodeRange{rune(0x0460), rune(0x0480)},
		UnicodeRange{rune(0x048a), rune(0x04c0)},
		UnicodeRange{rune(0x04c1), rune(0x052e)},
		UnicodeRange{rune(0x10a0), rune(0x10c5)},
		UnicodeRange{rune(0x1e00), rune(0x1efe)},
		UnicodeRange{rune(0x1f08), rune(0x1f0f)},
		UnicodeRange{rune(0x1f18), rune(0x1f1d)},
		UnicodeRange{rune(0x1f28), rune(0x1f2f)},
		UnicodeRange{rune(0x1f38), rune(0x1f3f)},
		UnicodeRange{rune(0x1f48), rune(0x1f4d)},
		UnicodeRange{rune(0x1f68), rune(0x1f6f)},
		UnicodeRange{rune(0x1f88), rune(0x1f8f)},
		UnicodeRange{rune(0x1f98), rune(0x1f9f)},
		UnicodeRange{rune(0x1fa8), rune(0x1faf)},
		UnicodeRange{rune(0x1fb8), rune(0x1fbc)},
		UnicodeRange{rune(0x1fc8), rune(0x1fcc)},
		UnicodeRange{rune(0x1fd8), rune(0x1fdb)},
		UnicodeRange{rune(0x1fe8), rune(0x1fec)},
		UnicodeRange{rune(0x1ff8), rune(0x1ffc)},
		UnicodeRange{rune(0x2102), rune(0x2107)},
		UnicodeRange{rune(0x210b), rune(0x2112)},
		UnicodeRange{rune(0x2115), rune(0x2115)},
		UnicodeRange{rune(0x2119), rune(0x211d)},
		UnicodeRange{rune(0x2124), rune(0x2124)},
		UnicodeRange{rune(0x2126), rune(0x2126)},
		UnicodeRange{rune(0x2128), rune(0x2128)},
		UnicodeRange{rune(0x212a), rune(0x212d)},
		UnicodeRange{rune(0x2130), rune(0x2133)},
		UnicodeRange{rune(0x213e), rune(0x213f)},
		UnicodeRange{rune(0x2145), rune(0x2145)},
		UnicodeRange{rune(0x2c00), rune(0x2c2e)},
		UnicodeRange{rune(0x2c60), rune(0x2c7f)},
		UnicodeRange{rune(0xa640), rune(0xa66c)},
		UnicodeRange{rune(0xa680), rune(0xa69a)},
		UnicodeRange{rune(0xa722), rune(0xa72e)},
		UnicodeRange{rune(0xa732), rune(0xa76e)},
		UnicodeRange{rune(0xa779), rune(0xa7ca)},
		UnicodeRange{rune(0xff21), rune(0xff3a)},
	]
}

fn negated_backend_class(excluded string, config Config) string {
	mut out := '[^${excluded}'
	if line_term := config.line_terminator {
		if line_term.is_crlf() {
			out += r'\r\n'
		} else {
			out += escaped_class_byte(line_term.as_byte())
		}
	}
	out += ']'
	return out
}

fn escaped_class_byte(byte u8) string {
	match byte {
		`\\`, `]`, `-`, `^` { return '\\${byte.ascii_str()}' }
		else { return byte.ascii_str() }
	}
}

fn is_extended_whitespace(b u8) bool {
	return b == ` ` || b == `\t` || b == `\n` || b == `\r` || b == `\f`
}

fn is_possessive_single_quantifier(pattern string, i int) bool {
	return pattern[i] in [`*`, `+`, `?`] && i + 1 < pattern.len && pattern[i + 1] == `+`
}

fn is_standalone_single_quantifier(pattern string, i int) bool {
	if i < 1 || pattern[i] !in [`*`, `+`, `?`] {
		return false
	}
	if pattern[i] == `?` && pattern[i - 1] == `(` {
		return false
	}
	return pattern[i - 1] !in [`*`, `+`, `?`, `{`, `}`]
}

fn braced_quantifier_end(pattern string, i int) ?usize {
	if i >= pattern.len || pattern[i] != `{` {
		return none
	}
	mut j := i + 1
	mut saw_digit := false
	for j < pattern.len && pattern[j] >= `0` && pattern[j] <= `9` {
		saw_digit = true
		j++
	}
	if !saw_digit {
		return none
	}
	if j < pattern.len && pattern[j] == `,` {
		j++
		for j < pattern.len && pattern[j] >= `0` && pattern[j] <= `9` {
			j++
		}
	}
	if j < pattern.len && pattern[j] == `}` {
		return usize(j)
	}
	return none
}

fn possessive_braced_quantifier_end(pattern string, i int) ?usize {
	if pattern[i] != `{` {
		return none
	}
	mut j := i + 1
	mut saw_digit := false
	for j < pattern.len && pattern[j] >= `0` && pattern[j] <= `9` {
		saw_digit = true
		j++
	}
	if !saw_digit {
		return none
	}
	if j < pattern.len && pattern[j] == `,` {
		j++
		for j < pattern.len && pattern[j] >= `0` && pattern[j] <= `9` {
			j++
		}
	}
	if j + 1 < pattern.len && pattern[j] == `}` && pattern[j + 1] == `+` {
		return usize(j)
	}
	return none
}

struct RegexErrorSpan {
	start int
	end   int
}

fn regex_parse_error(pattern string, spans []RegexErrorSpan, message string) Error {
	wrapped := '(?:${pattern})'
	mut marker := []u8{len: wrapped.len, init: ` `}
	mut last := 0
	for span in spans {
		start := if span.start < 0 { 0 } else { 3 + span.start }
		mut end := if span.end <= span.start { start + 1 } else { 3 + span.end }
		if end > marker.len {
			end = marker.len
		}
		for i in start .. end {
			marker[i] = `^`
		}
		if end > last {
			last = end
		}
	}
	if last == 0 {
		marker[0] = `^`
		last = 1
	}
	return Error.regex('regex parse error:\n    ${wrapped}\n    ${marker[..last].bytestr()}\nerror: ${message}')
}

fn find_rust_class_end(pattern string, start int) ?int {
	mut i := start + 1
	if i < pattern.len && pattern[i] == `^` {
		i++
	}
	// A closing bracket immediately after the optional negation is a literal.
	if i < pattern.len && pattern[i] == `]` {
		i++
	}
	for i < pattern.len {
		if pattern[i] == `\\` {
			i = skip_regex_escape(pattern, i)
			continue
		}
		if i + 1 < pattern.len && pattern[i] == `[` && pattern[i + 1] == `:` {
			mut posix_end := i + 2
			for posix_end + 1 < pattern.len {
				if pattern[posix_end] == `:` && pattern[posix_end + 1] == `]` {
					i = posix_end + 2
					break
				}
				posix_end++
			}
			if posix_end + 1 >= pattern.len {
				return none
			}
			continue
		}
		if pattern[i] == `[` {
			nested_end := find_rust_class_end(pattern, i) or { return none }
			i = nested_end + 1
			continue
		}
		if pattern[i] == `]` {
			return i
		}
		i++
	}
	return none
}

fn validate_rust_escape(pattern string, start int, end int, in_class bool, config Config) !int {
	if start + 1 >= end {
		return regex_parse_error(pattern, [RegexErrorSpan{-3, -2}], 'unclosed group')
	}
	next := pattern[start + 1]
	if in_class && next in [`A`, `B`, `b`, `z`] {
		return regex_parse_error(pattern, [RegexErrorSpan{start, start + 2}],
			'invalid escape sequence found in character class')
	}
	if next == `p` || next == `P` {
		property_escape := rust_property_escape_at(pattern, start) or {
			return regex_parse_error(pattern, [RegexErrorSpan{start, start + 2}],
				'invalid Unicode property escape')
		}
		if property_escape.next > end {
			return regex_parse_error(pattern, [RegexErrorSpan{start, end}],
				'invalid Unicode property escape')
		}
		if !rust_property_is_supported(property_escape.property, config) {
			return regex_parse_error(pattern, [RegexErrorSpan{start, property_escape.next}],
				'Unicode property not found')
		}
		return property_escape.next
	}
	if next >= `0` && next <= `9` && !in_class && !config.octal {
		return regex_parse_error(pattern, [RegexErrorSpan{start, start + 2}],
			'backreferences are not supported')
	}
	if next == `b` && !in_class && start + 2 < end && pattern[start + 2] == `{` {
		mut close := start + 3
		for close < end && pattern[close] != `}` {
			close++
		}
		if close < end && pattern[start + 3..close] in ['start', 'end', 'start-half',
			'end-half'] {
			return close + 1
		}
	}
	if next in [`x`, `u`, `U`] {
		if escape := rust_unicode_escape_at(pattern, start) {
			if escape.next <= end {
				return escape.next
			}
		}
		if next == `x` && start + 4 <= end {
			parse_hex_u32(pattern[start + 2..start + 4]) or {
				return regex_parse_error(pattern, [RegexErrorSpan{start, start + 4}],
					'invalid hexadecimal digit')
			}
			return start + 4
		}
		return regex_parse_error(pattern, [RegexErrorSpan{start, if start + 2 < end {
			start + 2
		} else {
			end
		}}], 'invalid hexadecimal digit')
	}
	if next >= `A` && next <= `Z` || next >= `a` && next <= `z` {
		if next !in [`A`, `B`, `D`, `S`, `W`, `a`, `b`, `d`, `f`, `n`, `r`, `s`, `t`, `v`,
			`w`, `z`] {
			return regex_parse_error(pattern, [RegexErrorSpan{start, start + 2}],
				'unrecognized escape sequence')
		}
	}
	return start + 2
}

fn validate_rust_class(pattern string, start int, end int, config Config) ! {
	mut i := start + 1
	if i < end && pattern[i] == `^` {
		i++
	}
	if i < end && pattern[i] == `]` {
		i++
	}
	for i < end {
		if pattern[i] == `\\` {
			i = validate_rust_escape(pattern, i, end, true, config)!
			continue
		}
		left_start := i
		left, left_next := parse_unicode_class_atom(pattern, i, end, config)
		if !left.ok || left_next <= i {
			return regex_parse_error(pattern, [RegexErrorSpan{i, i + 1}],
				'invalid character class')
		}
		i = left_next
		if i >= end || pattern[i] != `-` || i + 1 >= end || pattern[i + 1] == `-` {
			continue
		}
		right, right_next := parse_unicode_class_atom(pattern, i + 1, end, config)
		if !right.ok || right_next <= i + 1 {
			continue
		}
		if left.has_single && right.has_single && left.single > right.single {
			return regex_parse_error(pattern, [RegexErrorSpan{left_start, right_next}],
				'invalid character class range, the start must be <= the end')
		}
		i = right_next
	}
}

fn valid_capture_name_start(rn rune) bool {
	return rn == `_` || rn >= `A` && rn <= `Z` || rn >= `a` && rn <= `z` || rn > 0x7f
}

fn valid_capture_name_continue(rn rune) bool {
	return valid_capture_name_start(rn) || rn >= `0` && rn <= `9`
}

fn validate_capture_name(pattern string, start int, end int, mut names map[string]int) ! {
	if start == end {
		return regex_parse_error(pattern, [RegexErrorSpan{start, start + 1}],
			'empty capture group name')
	}
	mut i := start
	mut first := true
	for i < end {
		rn, width := read_pattern_rune_at(pattern, i)
		if width == 0 || (first && !valid_capture_name_start(rn))
			|| (!first && !valid_capture_name_continue(rn)) {
			return regex_parse_error(pattern, [RegexErrorSpan{i, i + if width > 0 { width } else { 1 }}],
				'invalid capture group character')
		}
		first = false
		i += width
	}
	name := pattern[start..end]
	if previous := names[name] {
		return regex_parse_error(pattern, [RegexErrorSpan{previous, previous + name.len},
			RegexErrorSpan{start, end}], 'duplicate capture group name')
	}
	names[name] = start
}

fn validate_rust_regex_syntax(pattern string, config Config) ! {
	mut i := 0
	// `build_many` parses each pattern inside a synthetic `(?:...)` group.
	// Keep that wrapper on the balance stack because a leading `)` and a
	// trailing `(` can balance against it (ripgrep issue #2480).
	mut groups := [-3]
	mut names := map[string]int{}
	mut can_repeat := false
	for i < pattern.len {
		ch := pattern[i]
		if ch == `\\` {
			escape_kind := if i + 1 < pattern.len { pattern[i + 1] } else { u8(0) }
			i = validate_rust_escape(pattern, i, pattern.len, false, config)!
			_ = escape_kind
			can_repeat = true
			continue
		}
		if ch == `[` {
			end := find_rust_class_end(pattern, i) or {
				return regex_parse_error(pattern, [RegexErrorSpan{i, pattern.len}],
					'unclosed character class')
			}
			validate_rust_class(pattern, i, end, config)!
			i = end + 1
			can_repeat = true
			continue
		}
		if ch in [`*`, `+`, `?`] {
			if !can_repeat {
				return regex_parse_error(pattern, [RegexErrorSpan{i, i + 1}],
					'repetition operator missing expression')
			}
			i++
			continue
		}
		if ch == `{` {
			mut j := i + 1
			min_start := j
			for j < pattern.len && pattern[j] >= `0` && pattern[j] <= `9` {
				j++
			}
			if j == min_start {
				return regex_parse_error(pattern, [RegexErrorSpan{i + 1, i + 2}],
					'repetition quantifier expects a valid decimal')
			}
			min_value := pattern[min_start..j].u64()
			mut max_value := min_value
			mut has_max := true
			if j < pattern.len && pattern[j] == `,` {
				j++
				max_start := j
				for j < pattern.len && pattern[j] >= `0` && pattern[j] <= `9` {
					j++
				}
				has_max = j > max_start
				if has_max {
					max_value = pattern[max_start..j].u64()
				}
			}
			if j >= pattern.len || pattern[j] != `}` {
				return regex_parse_error(pattern, [RegexErrorSpan{i + 1, i + 2}],
					'repetition quantifier expects a valid decimal')
			}
			if !can_repeat {
				return regex_parse_error(pattern, [RegexErrorSpan{i, j + 1}],
					'repetition operator missing expression')
			}
			if has_max && min_value > max_value {
				return regex_parse_error(pattern, [RegexErrorSpan{i, j + 1}],
					'invalid repetition count range, the start must be <= the end')
			}
			i = j + 1
			continue
		}
		if ch == `(` {
			if i + 1 >= pattern.len || pattern[i + 1] != `?` {
				groups << i
				if u32(groups.len - 1) > config.nest_limit {
					return regex_parse_error(pattern, [RegexErrorSpan{i, i + 1}],
						'exceed the maximum number of nested parentheses/brackets (${config.nest_limit})')
				}
				i++
				can_repeat = false
				continue
			}
			if i + 2 >= pattern.len {
				return regex_parse_error(pattern, [RegexErrorSpan{-3, -2}], 'unclosed group')
			}
			kind := pattern[i + 2]
			if kind in [`=`, `!`] || (kind == `<` && i + 3 < pattern.len
				&& pattern[i + 3] in [`=`, `!`]) {
				end := if kind == `<` { i + 4 } else { i + 3 }
				return regex_parse_error(pattern, [RegexErrorSpan{i, end}],
					'look-around, including look-ahead and look-behind, is not supported')
			}
			if kind == `P` && i + 3 < pattern.len && pattern[i + 3] in [`=`, `>`] {
				return regex_parse_error(pattern, [RegexErrorSpan{i + 2, i + 3}],
					'unrecognized flag')
			}
			if kind == `P` && i + 3 < pattern.len && pattern[i + 3] == `<` {
				name_start := i + 4
				name_end := pattern.index_after('>', name_start) or {
					return regex_parse_error(pattern, [RegexErrorSpan{-3, -2}], 'unclosed group')
				}
				validate_capture_name(pattern, name_start, name_end, mut names)!
				groups << i
				if u32(groups.len - 1) > config.nest_limit {
					return regex_parse_error(pattern, [RegexErrorSpan{i, name_end + 1}],
						'exceed the maximum number of nested parentheses/brackets (${config.nest_limit})')
				}
				i = name_end + 1
				can_repeat = false
				continue
			}
			if kind == `<` {
				name_start := i + 3
				name_end := pattern.index_after('>', name_start) or {
					return regex_parse_error(pattern, [RegexErrorSpan{-3, -2}], 'unclosed group')
				}
				validate_capture_name(pattern, name_start, name_end, mut names)!
				groups << i
				if u32(groups.len - 1) > config.nest_limit {
					return regex_parse_error(pattern, [RegexErrorSpan{i, name_end + 1}],
						'exceed the maximum number of nested parentheses/brackets (${config.nest_limit})')
				}
				i = name_end + 1
				can_repeat = false
				continue
			}
			if kind == `:` {
				groups << i
				if u32(groups.len - 1) > config.nest_limit {
					return regex_parse_error(pattern, [RegexErrorSpan{i, i + 3}],
						'exceed the maximum number of nested parentheses/brackets (${config.nest_limit})')
				}
				i += 3
				can_repeat = false
				continue
			}
			if is_pcre_only_group_kind(kind) || kind == `*` {
				return regex_parse_error(pattern, [RegexErrorSpan{i + 2, i + 3}],
					'unrecognized flag')
			}
			mut j := i + 2
			mut saw_flag := false
			for j < pattern.len && pattern[j] !in [`:`, `)`] {
				if pattern[j] !in [`i`, `m`, `s`, `U`, `u`, `x`, `R`, `-`] {
					return regex_parse_error(pattern, [RegexErrorSpan{j, j + 1}],
						'unrecognized flag')
				}
				saw_flag = true
				j++
			}
			if !saw_flag || j >= pattern.len {
				return regex_parse_error(pattern, [RegexErrorSpan{-3, -2}], 'unclosed group')
			}
			if pattern[j] == `:` {
				groups << i
				if u32(groups.len - 1) > config.nest_limit {
					return regex_parse_error(pattern, [RegexErrorSpan{i, j + 1}],
						'exceed the maximum number of nested parentheses/brackets (${config.nest_limit})')
				}
				can_repeat = false
			} else {
				can_repeat = false
			}
			i = j + 1
			continue
		}
		if ch == `)` {
			if groups.len == 0 {
				return regex_parse_error(pattern, [RegexErrorSpan{i, i + 1}], 'unopened group')
			}
			groups.pop()
			can_repeat = true
			i++
			continue
		}
		if ch == `|` {
			can_repeat = false
			i++
			continue
		}
		can_repeat = true
		i++
	}
	// Close the synthetic wrapper added by `build_many`.
	if groups.len == 0 {
		return regex_parse_error(pattern, [RegexErrorSpan{pattern.len, pattern.len + 1}],
			'unopened group')
	}
	groups.pop()
	if groups.len > 0 {
		return regex_parse_error(pattern, [RegexErrorSpan{-3, -2}], 'unclosed group')
	}
}

fn is_pcre_only_escape(ch u8) bool {
	return ch in [`C`, `E`, `G`, `K`, `N`, `Q`, `R`, `X`, `Z`, `g`, `h`, `H`, `k`, `V`]
}

fn is_pcre_only_group_kind(ch u8) bool {
	return ch in [`#`, `&`, `'`, `(`, `>`, `|`]
}

/// Returns true if the given literal string contains any byte from the line
/// terminator given.
fn has_line_terminator(lineterm matcher.LineTerminator, literal string) bool {
	if lineterm.is_crlf() {
		return literal.contains_u8(`\r`) || literal.contains_u8(`\n`)
	}
	return literal.contains_u8(lineterm.as_byte())
}

fn is_regex_meta_character(ch rune) bool {
	return ch in [`\\`, `.`, `+`, `*`, `?`, `(`, `)`, `|`, `[`, `]`, `{`, `}`, `^`, `$`,
		`#`, `&`, `-`, `~`]
}

fn escape_regex(literal string) string {
	mut out := []u8{cap: literal.len}
	for byte in literal.bytes() {
		match byte {
			`\\`, `.`, `+`, `*`, `?`, `(`, `)`, `|`, `[`, `]`, `{`, `}`, `^`, `$`, `#`,
			`&`, `-`, `~` {
				out << `\\`
				out << byte
			}
			else {
				out << byte
			}
		}
	}
	return out.bytestr()
}

fn strip_ignored_whitespace(pattern string) string {
	mut out := []u8{cap: pattern.len}
	mut i := 0
	mut in_class := false
	mut escaped := false
	for i < pattern.len {
		byte := pattern[i]
		if escaped {
			out << byte
			escaped = false
			i++
			continue
		}
		if byte == `\\` {
			out << byte
			escaped = true
			i++
			continue
		}
		if byte == `[` {
			in_class = true
			out << byte
			i++
			continue
		}
		if byte == `]` {
			in_class = false
			out << byte
			i++
			continue
		}
		if !in_class && byte == `#` {
			for i < pattern.len && pattern[i] != `\n` {
				i++
			}
			continue
		}
		if !in_class && byte in [` `, `\t`, `\n`, `\r`, `\v`, `\f`] {
			i++
			continue
		}
		out << byte
		i++
	}
	return out.bytestr()
}

fn ban_check(pattern string, byte u8) ! {
	mut i := 0
	for i < pattern.len {
		if pattern[i] == byte {
			return Error.new(ErrorKind.banned(byte))
		}
		if pattern[i] == `[` {
			class_set, ok, class_pos := parse_class_set(pattern, i + 1)
			if ok {
				mut count := 0
				for present in class_set {
					if present {
						count++
					}
				}
				if count == 1 && class_set[int(byte)] {
					return Error.new(ErrorKind.banned(byte))
				}
				i = class_pos
				continue
			}
		}
		if pattern[i] == `\\` {
			has_byte, escaped, next := parse_escape_byte(pattern, i)
			if has_byte && escaped == byte {
				return Error.new(ErrorKind.banned(byte))
			}
			i = next
			continue
		}
		i++
	}
}

// V-specific parser helper for class atoms in the port's local pattern checks.
struct ClassAtom {
	set        []bool
	single     u8
	has_single bool
	ok         bool
}

struct UnicodeClassAtom {
	ranges     []UnicodeRange
	single     rune
	has_single bool
	ok         bool
}

struct PatternReplacement {
	text string
	next int
}

fn normalize_posix_alpha_class_at(pattern string, start int, config Config) ?PatternReplacement {
	if start >= pattern.len || pattern[start] != `[` {
		return none
	}
	mut i := start + 1
	mut outer_negated := false
	if i < pattern.len && pattern[i] == `^` {
		outer_negated = true
		i++
	}
	if i + 3 >= pattern.len || pattern[i] != `[` || pattern[i + 1] != `:` {
		return none
	}
	i += 2
	mut inner_negated := false
	if i < pattern.len && pattern[i] == `^` {
		inner_negated = true
		i++
	}
	name_start := i
	for i + 1 < pattern.len && !(pattern[i] == `:` && pattern[i + 1] == `]`) {
		i++
	}
	if i + 2 >= pattern.len || pattern[i] != `:` || pattern[i + 1] != `]`
		|| pattern[i + 2] != `]` {
		return none
	}
	mut ranges := posix_class_ranges(pattern[name_start..i]) or { return none }
	if inner_negated != outer_negated {
		ranges = complement_unicode_ranges(ranges)
	}
	if line_term := config.line_terminator {
		terminators := if line_term.is_crlf() {
			[UnicodeRange{`\r`, `\r`}, UnicodeRange{`\n`, `\n`}]
		} else {
			[UnicodeRange{rune(line_term.as_byte()), rune(line_term.as_byte())}]
		}
		ranges = subtract_unicode_ranges(ranges, terminators)
	}
	return PatternReplacement{
		text: if ranges.len == 0 { r'(?:a^)' } else { '[${ranges_backend_class_body(ranges)}]' }
		next: i + 3
	}
}

fn posix_class_ranges(name string) ?[]UnicodeRange {
	return match name {
		'alnum' { [UnicodeRange{`0`, `9`}, UnicodeRange{`A`, `Z`}, UnicodeRange{`a`, `z`}] }
		'alpha' { [UnicodeRange{`A`, `Z`}, UnicodeRange{`a`, `z`}] }
		'ascii' { [UnicodeRange{rune(0), rune(0x7f)}] }
		'blank' { [UnicodeRange{`\t`, `\t`}, UnicodeRange{` `, ` `}] }
		'cntrl' { [UnicodeRange{rune(0), rune(0x1f)}, UnicodeRange{rune(0x7f), rune(0x7f)}] }
		'digit' { [UnicodeRange{`0`, `9`}] }
		'graph' { [UnicodeRange{rune(0x21), rune(0x7e)}] }
		'lower' { [UnicodeRange{`a`, `z`}] }
		'print' { [UnicodeRange{` `, rune(0x7e)}] }
		'punct' {
			[UnicodeRange{rune(0x21), rune(0x2f)}, UnicodeRange{rune(0x3a), rune(0x40)},
				UnicodeRange{rune(0x5b), rune(0x60)}, UnicodeRange{rune(0x7b), rune(0x7e)}]
		}
		'space' { [UnicodeRange{`\t`, `\r`}, UnicodeRange{` `, ` `}] }
		'upper' { [UnicodeRange{`A`, `Z`}] }
		'word' {
			[UnicodeRange{`0`, `9`}, UnicodeRange{`A`, `Z`}, UnicodeRange{`_`, `_`},
				UnicodeRange{`a`, `z`}]
		}
		'xdigit' { [UnicodeRange{`0`, `9`}, UnicodeRange{`A`, `F`}, UnicodeRange{`a`, `f`}] }
		else { return none }
	}
}

fn normalize_class_set_operation_at(pattern string, start int, config Config) ?PatternReplacement {
	if start >= pattern.len || pattern[start] != `[` {
		return none
	}
	end := find_class_end_nested(pattern, start) or { return none }
	body := pattern[start + 1..end]
	if !body.contains('&&') && !body.contains('--') && !body.contains('~~') {
		return none
	}
	class_set, ok, next := parse_unicode_class_set_expression(pattern, start + 1, end,
		config)
	if !ok || next != end {
		return none
	}
	mut stripped := class_set.clone()
	if line_term := config.line_terminator {
		terminators := if line_term.is_crlf() {
			[UnicodeRange{`\r`, `\r`}, UnicodeRange{`\n`, `\n`}]
		} else {
			[UnicodeRange{rune(line_term.as_byte()), rune(line_term.as_byte())}]
		}
		stripped = subtract_unicode_ranges(stripped, terminators)
	}
	return PatternReplacement{
		text: if stripped.len == 0 { r'(?:a^)' } else { '[${ranges_backend_class_body(stripped)}]' }
		next: end + 1
	}
}

fn normalize_unicode_class_at(pattern string, start int, config Config) ?PatternReplacement {
	if start >= pattern.len || pattern[start] != `[` {
		return none
	}
	end := find_class_end_nested(pattern, start) or { return none }
	class_set, ok, next := parse_unicode_class_set_expression(pattern, start + 1, end,
		config)
	if !ok || next != end {
		return none
	}
	mut stripped := class_set.clone()
	if line_term := config.line_terminator {
		terminators := if line_term.is_crlf() {
			[UnicodeRange{`\r`, `\r`}, UnicodeRange{`\n`, `\n`}]
		} else {
			[UnicodeRange{rune(line_term.as_byte()), rune(line_term.as_byte())}]
		}
		stripped = subtract_unicode_ranges(stripped, terminators)
	}
	return PatternReplacement{
		text: if stripped.len == 0 { r'(?:a^)' } else { '[${ranges_backend_class_body(stripped)}]' }
		next: end + 1
	}
}

fn parse_unicode_class_set_expression(pattern string, start int, end int, config Config) ([]UnicodeRange, bool, int) {
	mut i := start
	mut negated := false
	if i < end && pattern[i] == `^` {
		negated = true
		i++
	}
	mut ranges, ok, next := parse_unicode_class_union_until_operation(pattern, i, end,
		config)
	if !ok {
		return ranges, false, next
	}
	i = next
	for i < end {
		if i + 1 >= end {
			return ranges, false, i
		}
		op := pattern[i..i + 2]
		if op !in ['&&', '--', '~~'] {
			return ranges, false, i
		}
		right, right_ok, right_next := parse_unicode_class_union_until_operation(pattern,
			i + 2, end, config)
		if !right_ok {
			return ranges, false, right_next
		}
		ranges = match op {
			'&&' { intersect_unicode_ranges(ranges, right) }
			'--' { subtract_unicode_ranges(ranges, right) }
			'~~' { symmetric_difference_unicode_ranges(ranges, right) }
			else { ranges }
		}
		i = right_next
	}
	if negated {
		ranges = complement_unicode_ranges(ranges)
	}
	return ranges, true, i
}

fn parse_unicode_class_union_until_operation(pattern string, start int, end int, config Config) ([]UnicodeRange, bool, int) {
	mut i := start
	mut ranges := []UnicodeRange{}
	mut saw_atom := false
	for i < end {
		if i + 1 < end && pattern[i..i + 2] in ['&&', '--', '~~'] {
			break
		}
		start_atom, next_i := parse_unicode_class_atom(pattern, i, end, config)
		i = next_i
		if !start_atom.ok {
			return ranges, false, i
		}
		saw_atom = true
		if i + 1 < end && pattern[i] == `-` && pattern[i + 1] != `-` {
			i++
			end_atom, after_end := parse_unicode_class_atom(pattern, i, end, config)
			i = after_end
			if !end_atom.ok || !start_atom.has_single || !end_atom.has_single {
				return ranges, false, i
			}
			first := if start_atom.single < end_atom.single { start_atom.single } else { end_atom.single }
			last := if start_atom.single < end_atom.single { end_atom.single } else { start_atom.single }
			ranges = union_unicode_ranges(ranges, [UnicodeRange{first, last}])
		} else {
			ranges = union_unicode_ranges(ranges, start_atom.ranges)
		}
	}
	return ranges, saw_atom, i
}

fn parse_unicode_class_atom(pattern string, i int, end int, config Config) (UnicodeClassAtom, int) {
	if i >= end {
		return UnicodeClassAtom{}, i
	}
	if pattern[i] == `[` {
		if i + 3 < pattern.len && pattern[i + 1] == `:` {
			mut pos := i + 2
			mut negated := false
			if pos < pattern.len && pattern[pos] == `^` {
				negated = true
				pos++
			}
			name_start := pos
			for pos + 1 < pattern.len && !(pattern[pos] == `:` && pattern[pos + 1] == `]`) {
				pos++
			}
			if pos + 1 < pattern.len {
				mut ranges := posix_class_ranges(pattern[name_start..pos]) or {
					return UnicodeClassAtom{}, pos + 2
				}
				if negated {
					ranges = complement_unicode_ranges(ranges)
				}
				return UnicodeClassAtom{
					ranges: ranges
					ok:     true
				}, pos + 2
			}
		}
		nested_end := find_class_end_nested(pattern, i) or { return UnicodeClassAtom{}, end }
		nested, ok, next := parse_unicode_class_set_expression(pattern, i + 1, nested_end,
			config)
		return UnicodeClassAtom{
			ranges: nested
			ok:     ok && next == nested_end
		}, nested_end + 1
	}
	if pattern[i] == `\\` {
		return parse_unicode_escape_class(pattern, i, end, config)
	}
	value, width := read_pattern_rune_at(pattern, i)
	if width == 0 {
		return UnicodeClassAtom{}, end
	}
	return UnicodeClassAtom{
		ranges:     [UnicodeRange{value, value}]
		single:     value
		has_single: true
		ok:         true
	}, i + width
}

fn parse_unicode_escape_class(pattern string, i int, end int, config Config) (UnicodeClassAtom, int) {
	if i + 1 >= end {
		return UnicodeClassAtom{}, end
	}
	next := pattern[i + 1]
	if next == `p` || next == `P` {
		escape := rust_property_escape_at(pattern, i) or { return UnicodeClassAtom{}, skip_regex_escape(pattern, i) }
		if escape.next > end {
			return UnicodeClassAtom{}, end
		}
		encoded := rust_property_class_encoded(escape.property, config) or {
			return UnicodeClassAtom{}, escape.next
		}
		mut ranges := unicode_ranges_from_encoded(encoded)
		if next == `P` {
			ranges = complement_unicode_ranges(ranges)
		}
		return UnicodeClassAtom{
			ranges: ranges
			ok:     true
		}, escape.next
	}
	mut ranges := []UnicodeRange{}
	match next {
		`w`, `W` {
			ranges = if config.unicode {
				unicode_ranges_from_encoded(generated_unicode_word_encoded())
			} else {
				[UnicodeRange{`0`, `9`}, UnicodeRange{`A`, `Z`}, UnicodeRange{`_`, `_`},
					UnicodeRange{`a`, `z`}]
			}
			if next == `W` {
				ranges = complement_unicode_ranges(ranges)
			}
			return UnicodeClassAtom{
				ranges: ranges
				ok:     true
			}, i + 2
		}
		`d`, `D` {
			ranges = if config.unicode {
				unicode_ranges_from_encoded(generated_unicode_property_encoded('gc=Decimal_Number') or {
					return UnicodeClassAtom{}, i + 2
				})
			} else {
				[UnicodeRange{`0`, `9`}]
			}
			if next == `D` {
				ranges = complement_unicode_ranges(ranges)
			}
			return UnicodeClassAtom{
				ranges: ranges
				ok:     true
			}, i + 2
		}
		`s`, `S` {
			ranges = if config.unicode { whitespace_ranges() } else {
				[UnicodeRange{`\t`, `\t`}, UnicodeRange{`\n`, `\n`}, UnicodeRange{rune(0x0b), rune(0x0c)},
					UnicodeRange{`\r`, `\r`}, UnicodeRange{` `, ` `}]
			}
			if next == `S` {
				ranges = complement_unicode_ranges(ranges)
			}
			return UnicodeClassAtom{
				ranges: ranges
				ok:     true
			}, i + 2
		}
		else {}
	}
	if escape := rust_unicode_escape_at(pattern, i) {
		value := rune(escape.codepoint)
		return UnicodeClassAtom{
			ranges:     [UnicodeRange{value, value}]
			single:     value
			has_single: true
			ok:         true
		}, escape.next
	}
	has_byte, byte, next_i := parse_escape_byte(pattern, i)
	if !has_byte || next_i > end {
		return UnicodeClassAtom{}, if next_i > end { end } else { next_i }
	}
	value := rune(byte)
	return UnicodeClassAtom{
		ranges:     [UnicodeRange{value, value}]
		single:     value
		has_single: true
		ok:         true
	}, next_i
}

fn read_pattern_rune_at(pattern string, index int) (rune, int) {
	if index >= pattern.len {
		return rune(0), 0
	}
	b0 := u32(pattern[index])
	if b0 < 0x80 {
		return rune(b0), 1
	}
	if (b0 & 0xe0) == 0xc0 && index + 1 < pattern.len {
		return rune(((b0 & 0x1f) << 6) | (u32(pattern[index + 1]) & 0x3f)), 2
	}
	if (b0 & 0xf0) == 0xe0 && index + 2 < pattern.len {
		return rune(((b0 & 0x0f) << 12) | ((u32(pattern[index + 1]) & 0x3f) << 6) |
			(u32(pattern[index + 2]) & 0x3f)), 3
	}
	if (b0 & 0xf8) == 0xf0 && index + 3 < pattern.len {
		return rune(((b0 & 0x07) << 18) | ((u32(pattern[index + 1]) & 0x3f) << 12) |
			((u32(pattern[index + 2]) & 0x3f) << 6) | (u32(pattern[index + 3]) & 0x3f)), 4
	}
	return rune(0), 0
}

fn normalize_property_class_at(pattern string, start int, config Config) ?PatternReplacement {
	if start >= pattern.len || pattern[start] != `[` {
		return none
	}
	end := find_class_end_nested(pattern, start) or { return none }
	body := pattern[start + 1..end]
	if !body.contains(r'\p') && !body.contains(r'\P') {
		return none
	}
	mut out := []u8{cap: body.len}
	mut i := start + 1
	mut outer_negated := false
	if i < end && pattern[i] == `^` {
		outer_negated = true
		i++
	}
	if i < end && pattern[i] == `\\` && i + 1 < end
		&& (pattern[i + 1] == `p` || pattern[i + 1] == `P`) {
		property_escape := rust_property_escape_at(pattern, i) or { return none }
		if property_escape.next == end {
			body_part := rust_property_class_body(property_escape.property, config) or { return none }
			property_negated := pattern[i + 1] == `P`
			text := if property_negated != outer_negated {
				negated_backend_class(body_part, config)
			} else {
				'[${body_part}]'
			}
			return PatternReplacement{
				text: text
				next: end + 1
			}
		}
	}
	out << `[`
	if outer_negated {
		out << `^`
	}
	for i < end {
		if pattern[i] == `\\` && i + 1 < end {
			next := pattern[i + 1]
			if next == `p` || next == `P` {
				property_escape := rust_property_escape_at(pattern, i) or { return none }
				if property_escape.next > end {
					return none
				}
				if next == `P` {
					return none
				}
				body_part := rust_property_class_body(property_escape.property, config) or { return none }
				out << body_part.bytes()
				i = property_escape.next
				continue
			}
			out << pattern[i]
			out << next
			i += 2
			continue
		}
		out << pattern[i]
		i++
	}
	out << `]`
	return PatternReplacement{
		text: out.bytestr()
		next: end + 1
	}
}

fn find_class_end_nested(pattern string, start int) ?int {
	if start >= pattern.len || pattern[start] != `[` {
		return none
	}
	mut i := start + 1
	if i < pattern.len && pattern[i] == `^` {
		i++
	}
	if i < pattern.len && pattern[i] == `]` {
		i++
	}
	for i < pattern.len {
		if pattern[i] == `\\` {
			i = skip_regex_escape(pattern, i)
			continue
		}
		if i + 1 < pattern.len && pattern[i] == `[` && pattern[i + 1] == `:` {
			mut posix_end := i + 2
			for posix_end + 1 < pattern.len {
				if pattern[posix_end] == `:` && pattern[posix_end + 1] == `]` {
					i = posix_end + 2
					break
				}
				posix_end++
			}
			if posix_end + 1 >= pattern.len {
				return none
			}
			continue
		}
		if pattern[i] == `[` {
			nested_end := find_class_end_nested(pattern, i) or { return none }
			i = nested_end + 1
			continue
		}
		if pattern[i] == `]` {
			return i
		}
		i++
	}
	return none
}

fn skip_regex_escape(pattern string, start int) int {
	if start + 1 >= pattern.len {
		return pattern.len
	}
	next := pattern[start + 1]
	if next in [`p`, `P`, `u`] && start + 2 < pattern.len && pattern[start + 2] == `{` {
		mut i := start + 3
		for i < pattern.len && pattern[i] != `}` {
			i++
		}
		if i < pattern.len {
			return i + 1
		}
	}
	if next == `u` && start + 6 <= pattern.len {
		return start + 6
	}
	if next == `U` && start + 10 <= pattern.len {
		return start + 10
	}
	return start + 2
}

fn parse_class_set_expression(pattern string, start int, end int) ([]bool, bool, int) {
	mut i := start
	mut negated := false
	if i < end && pattern[i] == `^` {
		negated = true
		i++
	}
	mut set, ok, next := parse_class_union_until_operation(pattern, i, end)
	if !ok {
		return set, false, next
	}
	i = next
	for i < end {
		if i + 1 >= end {
			return set, false, i
		}
		op := pattern[i..i + 2]
		if op != '&&' && op != '--' && op != '~~' {
			return set, false, i
		}
		right, right_ok, right_next := parse_class_union_until_operation(pattern, i + 2, end)
		if !right_ok {
			return set, false, right_next
		}
		apply_class_set_operation(mut set, right, op)
		i = right_next
	}
	if negated {
		invert_byte_class(mut set)
	}
	return set, true, i
}

fn parse_class_union_until_operation(pattern string, start int, end int) ([]bool, bool, int) {
	mut i := start
	mut set := empty_byte_class()
	mut saw_atom := false
	for i < end {
		if i + 1 < end && ((pattern[i] == `&` && pattern[i + 1] == `&`)
			|| (pattern[i] == `-` && pattern[i + 1] == `-`) || (pattern[i] == `~`
			&& pattern[i + 1] == `~`)) {
			break
		}
		start_atom, next_i := parse_class_atom_bounded(pattern, i, end)
		i = next_i
		if !start_atom.ok {
			return set, false, i
		}
		saw_atom = true
		if i < end && pattern[i] == `-` && !(i + 1 < end && pattern[i + 1] == `-`) {
			i++
			end_atom, after_end := parse_class_atom_bounded(pattern, i, end)
			i = after_end
			if !end_atom.ok {
				return set, false, i
			}
			if start_atom.has_single && end_atom.has_single {
				add_byte_range(mut set, start_atom.single, end_atom.single)
			} else {
				add_byte_class(mut set, start_atom.set)
				add_byte_class(mut set, end_atom.set)
			}
		} else {
			add_byte_class(mut set, start_atom.set)
		}
	}
	return set, saw_atom, i
}

fn parse_class_atom_bounded(pattern string, i int, end int) (ClassAtom, int) {
	if i >= end {
		return ClassAtom{}, i
	}
	if pattern[i] == `[` {
		if i + 11 <= pattern.len && pattern[i..i + 11] == '[[:alpha:]]' {
			mut set := empty_byte_class()
			add_byte_range(mut set, `A`, `Z`)
			add_byte_range(mut set, `a`, `z`)
			return ClassAtom{
				set: set
				ok:  true
			}, i + 11
		}
		nested_end := find_class_end_nested(pattern, i) or { return ClassAtom{}, end }
		nested, ok, next := parse_class_set_expression(pattern, i + 1, nested_end)
		if !ok || next != nested_end {
			return ClassAtom{}, nested_end + 1
		}
		return ClassAtom{
			set: nested
			ok:  true
		}, nested_end + 1
	}
	if pattern[i] == `\\` {
		set, has_single, single, ok, next := parse_escape_class(pattern, i)
		if next > end {
			return ClassAtom{}, end
		}
		return ClassAtom{
			set:        set
			single:     single
			has_single: has_single
			ok:         ok
		}, next
	}
	byte := pattern[i]
	mut set := empty_byte_class()
	set[int(byte)] = true
	return ClassAtom{
		set:        set
		single:     byte
		has_single: true
		ok:         true
	}, i + 1
}

fn apply_class_set_operation(mut set []bool, right []bool, op string) {
	for i, present in right {
		match op {
			'&&' {
				set[i] = set[i] && present
			}
			'--' {
				if present {
					set[i] = false
				}
			}
			'~~' {
				set[i] = set[i] != present
			}
			else {}
		}
	}
}

fn parse_class_set(pattern string, start int) ([]bool, bool, int) {
	mut i := start
	mut negated := false
	if i < pattern.len && pattern[i] == `^` {
		negated = true
		i++
	}
	mut set := empty_byte_class()
	for i < pattern.len {
		if pattern[i] == `]` {
			i++
			if negated {
				invert_byte_class(mut set)
			}
			return set, true, i
		}
		start_atom, next_i := parse_class_atom(pattern, i)
		i = next_i
		if !start_atom.ok {
			return set, false, i
		}
		if i < pattern.len && pattern[i] == `-` && i + 1 < pattern.len && pattern[i + 1] != `]` {
			i++
			end_atom, after_end := parse_class_atom(pattern, i)
			i = after_end
			if !end_atom.ok {
				return set, false, i
			}
			if start_atom.has_single && end_atom.has_single {
				add_byte_range(mut set, start_atom.single, end_atom.single)
			} else {
				add_byte_class(mut set, start_atom.set)
				add_byte_class(mut set, end_atom.set)
			}
		} else {
			add_byte_class(mut set, start_atom.set)
		}
	}
	return set, false, i
}

fn parse_class_atom(pattern string, i int) (ClassAtom, int) {
	if i >= pattern.len {
		return ClassAtom{}, i
	}
	if pattern[i] == `[` {
		nested, ok, next := parse_class_set(pattern, i + 1)
		return ClassAtom{
			set: nested
			ok:  ok
		}, next
	}
	if pattern[i] == `\\` {
		set, has_single, single, ok, next := parse_escape_class(pattern, i)
		return ClassAtom{
			set:        set
			single:     single
			has_single: has_single
			ok:         ok
		}, next
	}
	byte := pattern[i]
	mut set := empty_byte_class()
	set[int(byte)] = true
	return ClassAtom{
		set:        set
		single:     byte
		has_single: true
		ok:         true
	}, i + 1
}

fn parse_escape_class(pattern string, i int) ([]bool, bool, u8, bool, int) {
	if i + 1 >= pattern.len {
		return full_byte_class(), false, u8(0), false, pattern.len
	}
	next := pattern[i + 1]
	match next {
		`d` {
			mut set := empty_byte_class()
			add_byte_range(mut set, `0`, `9`)
			return set, false, u8(0), true, i + 2
		}
		`D` {
			mut set := full_byte_class()
			for byte := `0`; byte <= `9`; byte++ {
				set[int(byte)] = false
			}
			return set, false, u8(0), true, i + 2
		}
		`s` {
			mut set := empty_byte_class()
			for byte in [`\t`, `\n`, 0x0b, 0x0c, `\r`, ` `] {
				set[int(byte)] = true
			}
			return set, false, u8(0), true, i + 2
		}
		`S` {
			mut set := full_byte_class()
			for byte in [`\t`, `\n`, 0x0b, 0x0c, `\r`, ` `] {
				set[int(byte)] = false
			}
			return set, false, u8(0), true, i + 2
		}
		`w` {
			mut set := empty_byte_class()
			add_word_bytes(mut set)
			return set, false, u8(0), true, i + 2
		}
		`W` {
			mut set := full_byte_class()
			mut word := empty_byte_class()
			add_word_bytes(mut word)
			for index, present in word {
				if present {
					set[index] = false
				}
			}
			return set, false, u8(0), true, i + 2
		}
		`p`, `P` {
			if end := rust_property_escape_end(pattern, i) {
				property := pattern[i + 3..int(end) - 1]
				if mut set := rust_property_byte_class(property) {
					if next == `P` {
						invert_byte_class(mut set)
					}
					return set, false, u8(0), true, int(end)
				}
			} else if i + 3 <= pattern.len && pattern[i..i + 3] == r'\pL' {
				mut set := empty_byte_class()
				add_byte_range(mut set, `A`, `Z`)
				add_byte_range(mut set, `a`, `z`)
				return set, false, u8(0), true, i + 3
			}
			return full_byte_class(), false, u8(0), false, skip_regex_escape(pattern, i)
		}
		else {
			has_byte, byte, next_i := parse_escape_byte(pattern, i)
			if !has_byte {
				return full_byte_class(), false, u8(0), true, next_i
			}
			mut set := empty_byte_class()
			set[int(byte)] = true
			return set, true, byte, true, next_i
		}
	}
}

fn parse_escape_byte(pattern string, i int) (bool, u8, int) {
	if i + 1 >= pattern.len {
		return false, u8(0), pattern.len
	}
	next := pattern[i + 1]
	if escaped := escaped_byte(next) {
		return true, escaped, i + 2
	}
	if next == `x` {
		if i + 2 < pattern.len && pattern[i + 2] == `{` {
			mut end := i + 3
			for end < pattern.len && pattern[end] != `}` {
				end++
			}
			if end < pattern.len {
				value := parse_hex_u32(pattern[i + 3..end]) or { return false, u8(0), end + 1 }
				if value <= 0xff {
					return true, u8(value), end + 1
				}
				return false, u8(0), end + 1
			}
		}
		if i + 4 <= pattern.len {
			value := parse_hex_u32(pattern[i + 2..i + 4]) or { return false, u8(0), i + 4 }
			if value <= 0xff {
				return true, u8(value), i + 4
			}
			return false, u8(0), i + 4
		}
	}
	if next == `u` {
		if i + 2 < pattern.len && pattern[i + 2] == `{` {
			mut end := i + 3
			for end < pattern.len && pattern[end] != `}` {
				end++
			}
			if end < pattern.len {
				value := parse_hex_u32(pattern[i + 3..end]) or { return false, u8(0), end + 1 }
				if value <= 0xff {
					return true, u8(value), end + 1
				}
				return false, u8(0), end + 1
			}
		}
		if i + 6 > pattern.len {
			return false, u8(0), pattern.len
		}
		value := parse_hex_u32(pattern[i + 2..i + 6]) or { return false, u8(0), i + 6 }
		if value <= 0xff {
			return true, u8(value), i + 6
		}
		return false, u8(0), i + 6
	}
	if next == `U` && i + 10 <= pattern.len {
		value := parse_hex_u32(pattern[i + 2..i + 10]) or { return false, u8(0), i + 10 }
		if value <= 0xff {
			return true, u8(value), i + 10
		}
		return false, u8(0), i + 10
	}
	return true, next, i + 2
}

fn empty_byte_class() []bool {
	return []bool{len: 256}
}

fn full_byte_class() []bool {
	return []bool{len: 256, init: true}
}

fn invert_byte_class(mut set []bool) {
	for i in 0 .. set.len {
		set[i] = !set[i]
	}
}

fn add_byte_class(mut set []bool, other []bool) {
	for i, present in other {
		if present {
			set[i] = true
		}
	}
}

fn add_byte_range(mut set []bool, start u8, end u8) {
	if start <= end {
		for byte := start; byte <= end; byte++ {
			set[int(byte)] = true
		}
		return
	}
	for byte := end; byte <= start; byte++ {
		set[int(byte)] = true
	}
}

fn add_word_bytes(mut set []bool) {
	add_byte_range(mut set, `A`, `Z`)
	add_byte_range(mut set, `a`, `z`)
	add_byte_range(mut set, `0`, `9`)
	set[int(`_`)] = true
}

fn rust_property_byte_class(property string) ?[]bool {
	mut set := empty_byte_class()
	match normalize_property_name(property) {
		'any' {
			return full_byte_class()
		}
		'ascii' {
			add_byte_range(mut set, u8(0), u8(0x7f))
			return set
		}
		'decimalnumber', 'gc=nd', 'generalcategory=nd', 'nd' {
			add_byte_range(mut set, `0`, `9`)
			return set
		}
		'l', 'letter', 'alphabetic', 'alpha' {
			add_byte_range(mut set, `A`, `Z`)
			add_byte_range(mut set, `a`, `z`)
			return set
		}
		'gc=lu', 'generalcategory=lu', 'lu', 'uppercaseletter' {
			add_byte_range(mut set, `A`, `Z`)
			return set
		}
		else {
			return none
		}
	}
}

fn byte_class_to_backend_pattern(set []bool) string {
	mut any := false
	for present in set {
		if present {
			any = true
			break
		}
	}
	if !any {
		return r'(?:a^)'
	}
	mut out := []u8{cap: 64}
	out << `[`
	mut i := 0
	for i < set.len {
		if !set[i] {
			i++
			continue
		}
		start := u8(i)
		mut end := i
		for end + 1 < set.len && set[end + 1] {
			end++
		}
		append_backend_class_byte(mut out, start)
		if end > i {
			out << `-`
			append_backend_class_byte(mut out, u8(end))
		}
		i = end + 1
	}
	out << `]`
	return out.bytestr()
}

fn append_backend_class_byte(mut out []u8, byte u8) {
	match byte {
		`\\`, `]`, `-`, `^` {
			out << `\\`
			out << byte
		}
		`\n` {
			out << `\\`
			out << `n`
		}
		`\r` {
			out << `\\`
			out << `r`
		}
		`\t` {
			out << `\\`
			out << `t`
		}
		else {
			if byte < 0x20 || byte >= 0x7f {
				hex := '0123456789ABCDEF'
				out << `\\`
				out << `x`
				out << hex[int(byte >> 4)]
				out << hex[int(byte & 0x0f)]
			} else {
				out << byte
			}
		}
	}
}

fn strip_line_terminator_from_match(pattern string, config Config) !string {
	line_term := config.line_terminator or { return pattern.clone() }
	mut out := []u8{cap: pattern.len}
	mut i := 0
	mut in_class := false
	for i < pattern.len {
		byte := pattern[i]
		if byte == `[` {
			if replacement := normalize_class_without_line_term_at(pattern, i, config) {
				out << replacement.text.bytes()
				i = replacement.next
				continue
			}
			class, next := strip_class_line_terminator(pattern, i, line_term)!
			out << class.bytes()
			i = next
			continue
		}
		if byte == `]` {
			in_class = false
			out << byte
			i++
			continue
		}
		if byte == `\\` && i + 1 < pattern.len {
			next := pattern[i + 1]
			if next in [`p`, `P`] {
				if replacement := normalize_property_without_line_term_at(pattern, i, config) {
					out << replacement.text.bytes()
					i = replacement.next
					continue
				}
			}
			if next == `s` {
				if line_term_can_match_ascii_whitespace(line_term) {
					append_ascii_whitespace_class_without_line_term(mut out, line_term, true)
				} else {
					out << `\\`
					out << next
				}
				i += 2
				continue
			}
			has_byte, escaped, next_i := parse_escape_byte(pattern, i)
			if has_byte {
				if line_term_rejects_byte(line_term, escaped) {
					return Error.new(ErrorKind.not_allowed([escaped].bytestr()))
				}
			}
			for j in i .. next_i {
				out << pattern[j]
			}
			i = next_i
			continue
		}
		if !in_class && line_term_rejects_byte(line_term, byte) {
			return Error.new(ErrorKind.not_allowed([byte].bytestr()))
		}
		out << byte
		i++
	}
	return out.bytestr()
}

fn normalize_property_without_line_term_at(pattern string, start int, config Config) ?PatternReplacement {
	line_term := config.line_terminator or { return none }
	escape := rust_property_escape_at(pattern, start) or { return none }
	mut ranges := if normalize_property_name(escape.property) == 'any' {
		[UnicodeRange{rune(0), rune(0x10ffff)}]
	} else {
		encoded := rust_property_class_encoded(escape.property, config) or { return none }
		unicode_ranges_from_encoded(encoded)
	}
	if pattern[start + 1] == `P` {
		ranges = complement_unicode_ranges(ranges)
	}
	terminators := if line_term.is_crlf() {
		[UnicodeRange{`\n`, `\n`}, UnicodeRange{`\r`, `\r`}]
	} else {
		[UnicodeRange{rune(line_term.as_byte()), rune(line_term.as_byte())}]
	}
	ranges = subtract_unicode_ranges(ranges, terminators)
	if ranges.len == 0 {
		return none
	}
	return PatternReplacement{
		text: '[${ranges_backend_class_body(ranges)}]'
		next: escape.next
	}
}

fn normalize_class_without_line_term_at(pattern string, start int, config Config) ?PatternReplacement {
	line_term := config.line_terminator or { return none }
	end := find_class_end_nested(pattern, start) or { return none }
	mut ranges, ok, next := parse_unicode_class_set_expression(pattern, start + 1, end,
		config)
	if !ok || next != end {
		return none
	}
	terminators := if line_term.is_crlf() {
		[UnicodeRange{`\n`, `\n`}, UnicodeRange{`\r`, `\r`}]
	} else {
		[UnicodeRange{rune(line_term.as_byte()), rune(line_term.as_byte())}]
	}
	ranges = subtract_unicode_ranges(ranges, terminators)
	if ranges.len == 0 {
		return none
	}
	return PatternReplacement{
		text: '[${ranges_backend_class_body(ranges)}]'
		next: end + 1
	}
}

fn strip_class_line_terminator(pattern string, start int, line_term matcher.LineTerminator) !(string, int) {
	mut out := []u8{cap: pattern.len - start}
	out << `[`
	mut i := start + 1
	mut negated := false
	if i < pattern.len && pattern[i] == `^` {
		negated = true
		out << `^`
		i++
	}
	mut kept := 0
	mut excluded_line_term := false
	for i < pattern.len {
		if pattern[i] == `]` {
			if negated {
				if line_term.is_crlf() {
					if !excluded_line_term {
						out << `\\`
						out << `r`
						out << `\\`
						out << `n`
					}
				} else if !excluded_line_term {
					append_escaped_byte(mut out, line_term.as_byte())
				}
			} else if kept == 0 {
				return Error.new(ErrorKind.not_allowed(line_term.as_bytes().bytestr()))
			}
			out << `]`
			return out.bytestr(), i + 1
		}
		if pattern[i] == `\\` && i + 1 < pattern.len {
			next := pattern[i + 1]
			if next == `s` {
				if line_term_can_match_ascii_whitespace(line_term) {
					append_ascii_whitespace_class_without_line_term(mut out, line_term, false)
				} else {
					out << pattern[i]
					out << next
				}
				kept++
				i += 2
				continue
			}
			if is_byte_escape_start(next) {
				has_byte, escaped, next_i := parse_escape_byte(pattern, i)
				if has_byte && line_term_rejects_byte(line_term, escaped) {
					excluded_line_term = true
					i = next_i
					continue
				}
				for j in i .. next_i {
					out << pattern[j]
				}
				kept++
				i = next_i
				continue
			}
			if escaped := escaped_byte(next) {
				if line_term_rejects_byte(line_term, escaped) {
					excluded_line_term = true
					i += 2
					continue
				}
			}
			out << pattern[i]
			out << next
			kept++
			i += 2
			continue
		}
		if line_term_rejects_byte(line_term, pattern[i]) {
			excluded_line_term = true
			i++
			continue
		}
		out << pattern[i]
		kept++
		i++
	}
	return Error.new(ErrorKind.not_allowed(line_term.as_bytes().bytestr()))
}

fn is_byte_escape_start(byte u8) bool {
	return byte == `x` || byte == `u` || byte == `U`
}

fn line_term_can_match_ascii_whitespace(line_term matcher.LineTerminator) bool {
	if line_term.is_crlf() {
		return true
	}
	return line_term.as_byte() in [` `, `\t`, `\r`, u8(0x0b), u8(0x0c), `\n`]
}

fn append_ascii_whitespace_class_without_line_term(mut out []u8, line_term matcher.LineTerminator, wrap bool) {
	if wrap {
		out << `[`
	}
	for byte in [` `, `\t`, `\r`, u8(0x0b), u8(0x0c), `\n`] {
		if !line_term_rejects_byte(line_term, byte) {
			out << byte
		}
	}
	if wrap {
		out << `]`
	}
}

fn append_escaped_byte(mut out []u8, byte u8) {
	match byte {
		`\n` {
			out << `\\`
			out << `n`
		}
		`\r` {
			out << `\\`
			out << `r`
		}
		`\t` {
			out << `\\`
			out << `t`
		}
		else {
			out << byte
		}
	}
}

fn escaped_byte(byte u8) ?u8 {
	return match byte {
		`a` { u8(`\a`) }
		`f` { u8(`\f`) }
		`n` { u8(`\n`) }
		`r` { u8(`\r`) }
		`t` { u8(`\t`) }
		`v` { u8(`\v`) }
		else { none }
	}
}

fn line_term_rejects_byte(line_term matcher.LineTerminator, byte u8) bool {
	if line_term.is_crlf() {
		return byte == `\r` || byte == `\n`
	}
	return byte == line_term.as_byte()
}
