module regex

import matcher
import regex.pcre

/// Config represents the configuration of a regex matcher in this crate.
/// The configuration is itself a rough combination of the knobs found in
/// the `regex` crate itself, along with additional `grep-matcher` specific
/// options.
///
/// The configuration can be used to build a "configured" HIR expression. A
/// configured HIR expression is an HIR expression that is aware of the
/// configuration which generated it, and provides transformation on that HIR
/// such that the configuration is preserved.
pub struct Config implements IClone {
pub mut:
	case_insensitive     bool
	case_smart           bool
	multi_line           bool
	dot_matches_new_line bool
	swap_greed           bool
	ignore_whitespace    bool
	unicode              bool
	octal                bool
	size_limit           usize
	dfa_size_limit       usize
	nest_limit           u32
	line_terminator      ?matcher.LineTerminator
	ban                  ?u8
	crlf                 bool
	word                 bool
	fixed_strings        bool
	whole_line           bool
}

pub fn Config.default() Config {
	return Config{
		unicode:        true
		size_limit:     usize(100 * (1 << 20))
		dfa_size_limit: usize(1000 * (1 << 20))
		nest_limit:     u32(250)
		line_terminator: none
		ban:             none
	}
}

// V-specific: keep an explicit clone while V2 mark-used/codegen can resolve
// generated clone helpers for same-named structs across modules inconsistently.
pub fn (config Config) clone() Config {
	return Config{
		case_insensitive:     config.case_insensitive
		case_smart:           config.case_smart
		multi_line:           config.multi_line
		dot_matches_new_line: config.dot_matches_new_line
		swap_greed:           config.swap_greed
		ignore_whitespace:    config.ignore_whitespace
		unicode:              config.unicode
		octal:                config.octal
		size_limit:           config.size_limit
		dfa_size_limit:       config.dfa_size_limit
		nest_limit:           config.nest_limit
		line_terminator:      config.line_terminator
		ban:                  config.ban
		crlf:                 config.crlf
		word:                 config.word
		fixed_strings:        config.fixed_strings
		whole_line:           config.whole_line
	}
}

/// Use this configuration to build an HIR from the given patterns. The HIR
/// returned corresponds to a single regex that is an alternation of the
/// patterns given.
pub fn (config Config) build_many(patterns []string) !ConfiguredHIR {
	return ConfiguredHIR.new(config.clone(), patterns)
}

/// Accounting for the `smart_case` config knob, return true if and only if
/// this pattern should be matched case insensitively.
fn (config Config) is_case_insensitive(analysis AstAnalysis) bool {
	if config.case_insensitive {
		return true
	}
	if !config.case_smart {
		return false
	}
	return analysis.any_literal() && !analysis.any_uppercase()
}

/// Returns whether the given patterns should be treated as "fixed strings"
/// literals. This is different from just querying the `fixed_strings` knob
/// in that if the knob is false, this will still return true in some cases
/// if the patterns are themselves indistinguishable from literals.
///
/// The main idea here is that if this returns true, then it is safe
/// to build an `regex_syntax::hir::Hir` value directly from the given
/// patterns as an alternation of `hir::Literal` values.
fn (config Config) is_fixed_strings(patterns []string) bool {
	// When these are enabled, we really need to parse the patterns and
	// let them go through the standard HIR translation process in order
	// for case folding transforms to be applied.
	if config.case_insensitive || config.case_smart {
		return false
	}
	// Even if whole_line or word is enabled, both of those things can
	// be implemented by wrapping the Hir generated by an alternation of
	// fixed string literals. So for here at least, we don't care about the
	// word or whole_line settings.
	if config.fixed_strings {
		// ... but if any literal contains a line terminator, then we've
		// got to bail out because this will ultimately result in an error.
		if lineterm := config.line_terminator {
			for p in patterns {
				if has_line_terminator(lineterm, p) {
					return false
				}
			}
		}
		return true
	}
	// In this case, the only way we can hand construct the Hir is if none
	// of the patterns contain meta characters. If they do, then we need to
	// send them through the standard parsing/translation process.
	for p in patterns {
		for ch in p {
			if is_regex_meta_character(ch) {
				return false
			}
		}
		// Same deal as when fixed_strings is set above. If the pattern has
		// a line terminator anywhere, then we need to bail out and let
		// an error occur.
		if lineterm := config.line_terminator {
			if has_line_terminator(lineterm, p) {
				return false
			}
		}
	}
	return true
}

/// A "configured" HIR expression, which is aware of the configuration which
/// produced this HIR.
///
/// Since the configuration is tracked, values with this type can be
/// transformed into other HIR expressions (or regular expressions) in a way
/// that preserves the configuration. For example, the `fast_line_regex`
/// method will apply literal extraction to the inner HIR and use that to build
/// a new regex that matches the extracted literals in a way that is
/// consistent with the configuration that produced this HIR. For example, the
/// size limits set on the configured HIR will be propagated out to any
/// subsequently constructed HIR or regular expression.
pub struct ConfiguredHIR implements IClone {
	config Config
	hir    Hir
}

/// Parse the given patterns into a single HIR expression that represents
/// an alternation of the patterns given.
fn ConfiguredHIR.new(config Config, patterns []string) !ConfiguredHIR {
	mut hir := Hir.empty()
	if config.is_fixed_strings(patterns) {
		hir = Hir.from_fixed_literals(patterns)
	} else {
		mut alts := []string{cap: patterns.len}
		for p in patterns {
			if config.fixed_strings {
				alts << '(?:${escape_regex(p)})'
			} else {
				validate_rust_regex_syntax(p, config)!
				alts << '(?:${p})'
			}
		}
		mut pattern := if alts.len == 0 { '' } else { alts.join('|') }
		if config.ignore_whitespace {
			pattern = strip_ignored_whitespace(pattern)
		}
		hir = Hir.from_pattern(pattern, config)
	}
	if banned := config.ban {
		ban_check(hir.to_regex(), banned)!
	}
	if line_term := config.line_terminator {
		stripped := strip_line_terminator_from_match(hir.to_regex(), line_term)!
		hir = Hir.from_pattern(stripped, config)
	}
	return ConfiguredHIR{
		config: config
		hir:    hir
	}
}

/// Return a reference to the underlying configuration.
pub fn (chir &^a ConfiguredHIR) config[^a]() &^a Config {
	return &chir.config
}

/// Return a reference to the underlying HIR.
pub fn (chir &^a ConfiguredHIR) hir[^a]() &^a Hir {
	return &chir.hir
}

/// Convert this HIR to a regex that can be used for matching.
pub fn (chir ConfiguredHIR) to_regex() !pcre.Regex {
	pattern := chir.backend_pattern()
	return pcre.compile(pattern) or { return Error.regex(err.msg()) }
}

/// Compute the set of non-matching bytes for this HIR expression.
pub fn (chir ConfiguredHIR) non_matching_bytes() matcher.ByteSet {
	return chir.hir.non_matching_bytes()
}

/// Returns the line terminator configured on this expression.
///
/// When we have beginning/end anchors (NOT line anchors), the fast line
/// searching path isn't quite correct. Or at least, doesn't match the slow
/// path. Namely, the slow path strips line terminators while the fast path
/// does not. Since '$' (when multi-line mode is disabled) doesn't match at
/// line boundaries, the existence of a line terminator might cause it to
/// not match when it otherwise would with the line terminator stripped.
///
/// Since searching with text anchors is exceptionally rare in the context
/// of line oriented searching (multi-line mode is basically always
/// enabled), we just disable this optimization when there are text
/// anchors. We disable it by not returning a line terminator, since
/// without a line terminator, the fast search path can't be executed.
///
/// Actually, the above is no longer quite correct. Later on, another
/// optimization was added where if the line terminator was in the set of
/// bytes that was guaranteed to never be part of a match, then the higher
/// level search infrastructure assumes that the fast line-by-line search
/// path can still be taken. This optimization applies when multi-line
/// search (not multi-line mode) is enabled. In that case, there is no
/// configured line terminator since the regex is permitted to match a
/// line terminator. But if the regex is guaranteed to never match across
/// multiple lines despite multi-line search being requested, we can still
/// do the faster and more flexible line-by-line search. This is why the
/// non-matching extraction routine removes `\n` when `\A` and `\z` are
/// present even though that's not quite correct...
///
/// See: <https://github.com/BurntSushi/ripgrep/issues/2260>
pub fn (chir ConfiguredHIR) line_terminator() ?matcher.LineTerminator {
	if chir.hir.contains_haystack_anchor() {
		return none
	}
	return chir.config.line_terminator
}

/// Turns this configured HIR into an equivalent one, but where it must
/// match at the start and end of a line.
pub fn (chir ConfiguredHIR) into_whole_line() ConfiguredHIR {
	return ConfiguredHIR{
		config: chir.config.clone()
		hir:    chir.hir.into_whole_line(chir.config)
	}
}

/// Turns this configured HIR into an equivalent one, but where it must
/// match at word boundaries.
pub fn (chir ConfiguredHIR) into_word() ConfiguredHIR {
	// V-specific: the local backend does not reliably support the look-around
	// assertions needed for half-word boundaries without changing match
	// offsets, so word-boundary enforcement is applied by
	// RegexMatcher.accept_match.
	return chir
}

fn (chir ConfiguredHIR) backend_pattern() string {
	mut flags := ''
	pattern := normalize_backend_pattern(chir.hir.to_regex(), chir.config)
	analysis := AstAnalysis.from_pattern(pattern) or { AstAnalysis.new() }
	if chir.config.is_case_insensitive(analysis) {
		flags += 'i'
	}
	if chir.config.multi_line || chir.config.crlf {
		flags += 'm'
	}
	if chir.config.dot_matches_new_line {
		flags += 's'
	}
	if flags.len == 0 {
		return pattern
	}
	return '(?${flags})${pattern}'
}

fn normalize_backend_pattern(pattern string, config Config) string {
	mut out := []u8{cap: pattern.len}
	mut i := 0
	mut in_class := false
	mut escaped := false
	mut inline_ignore_whitespace := false
	mut inline_crlf := false
	for i < pattern.len {
		ch := pattern[i]
		if !escaped && !in_class && i + 4 <= pattern.len && pattern[i..i + 4] == '(?x)' {
			inline_ignore_whitespace = true
			i += 4
			escaped = false
			continue
		}
		if !escaped && !in_class && i + 5 <= pattern.len && pattern[i..i + 5] == '(?-i)' {
			i += 5
			escaped = false
			continue
		}
		if !escaped && !in_class && i + 4 <= pattern.len && pattern[i..i + 4] == '(?R)' {
			inline_crlf = true
			i += 4
			escaped = false
			continue
		}
		if !escaped && !in_class && i + 5 <= pattern.len && pattern[i..i + 5] == '(?-R)' {
			inline_crlf = false
			i += 5
			escaped = false
			continue
		}
		if !escaped && !in_class && i + 4 <= pattern.len && pattern[i..i + 4] == '(?U)' {
			i += 4
			escaped = false
			continue
		}
		if !escaped && !in_class && i + 6 <= pattern.len && pattern[i..i + 6] == '(?i-m)' {
			out << '(?i)'.bytes()
			i += 6
			escaped = false
			continue
		}
		if !escaped && !in_class && ch == `[` {
			if replacement := normalize_posix_alpha_class_at(pattern, i, config) {
				out << replacement.text.bytes()
				i = replacement.next
				escaped = false
				continue
			}
			if replacement := normalize_class_set_operation_at(pattern, i, config) {
				out << replacement.text.bytes()
				i = replacement.next
				escaped = false
				continue
			}
		}
		if !escaped && !in_class && i + 4 <= pattern.len && pattern[i..i + 4] == '(?x:' {
			if end := matching_group_end(pattern, i) {
				inner := strip_ignored_whitespace(pattern[i + 4..int(end)])
				out << '(?:'.bytes()
				out << normalize_backend_pattern(inner, config).bytes()
				out << `)`
				i = int(end) + 1
				escaped = false
				continue
			}
		}
		if !escaped && !in_class && i + 5 <= pattern.len && pattern[i..i + 5] == '(?-x:' {
			if end := matching_group_end(pattern, i) {
				out << '(?:'.bytes()
				out << normalize_backend_pattern(pattern[i + 5..int(end)], config).bytes()
				out << `)`
				i = int(end) + 1
				escaped = false
				continue
			}
		}
		if !escaped && !in_class && i + 5 <= pattern.len && pattern[i..i + 5] == '(?-i:' {
			if end := matching_group_end(pattern, i) {
				out << '(?:'.bytes()
				out << normalize_backend_pattern(pattern[i + 5..int(end)], config).bytes()
				out << `)`
				i = int(end) + 1
				escaped = false
				continue
			}
		}
		if !escaped && !in_class && i + 4 <= pattern.len && pattern[i..i + 4] == '(?R:' {
			if end := matching_group_end(pattern, i) {
				mut inner_config := config
				inner_config.crlf = true
				out << '(?:'.bytes()
				out << normalize_backend_pattern(pattern[i + 4..int(end)], inner_config).bytes()
				out << `)`
				i = int(end) + 1
				escaped = false
				continue
			}
		}
		if inline_ignore_whitespace && !escaped && !in_class && is_extended_whitespace(ch) {
			i++
			escaped = false
			continue
		}
		if (config.crlf || inline_crlf) && !escaped && !in_class && ch == `$` {
			out << r'\x0D?$'.bytes()
			i++
			continue
		}
		if !escaped && !in_class && i + 3 < pattern.len && ch == `(` && pattern[i + 1] == `?`
			&& pattern[i + 2] == `<` && pattern[i + 3] != `=` && pattern[i + 3] != `!` {
			out << '(?P<'.bytes()
			i += 3
			escaped = false
			continue
		}
		if !escaped && ch == `[` {
			in_class = true
		} else if !escaped && ch == `]` {
			in_class = false
		}
		if !escaped && !in_class && ch == `\\` {
			if end := rust_word_boundary_variant_end(pattern, i) {
				out << r'\b'.bytes()
				i = int(end)
				escaped = false
				continue
			}
			if i + 1 < pattern.len {
				next := pattern[i + 1]
				match next {
					`A` {
						out << `^`
						i += 2
						escaped = false
						continue
					}
					`z` {
						out << `$`
						i += 2
						escaped = false
						continue
					}
					`<`, `>` {
						out << r'\b'.bytes()
						i += 2
						escaped = false
						continue
					}
					`d` {
						out << '[0-9]'.bytes()
						i += 2
						escaped = false
						continue
					}
					`D` {
						out << negated_backend_class('0-9', config).bytes()
						i += 2
						escaped = false
						continue
					}
					`w` {
						out << word_backend_class(config).bytes()
						i += 2
						escaped = false
						continue
					}
					`W` {
						out << negated_backend_class(word_backend_class_body(config), config).bytes()
						i += 2
						escaped = false
						continue
					}
					`p`, `P` {
						if end := rust_property_escape_end(pattern, i) {
							property := pattern[i + 3..int(end) - 1]
							if next == `p` {
								if replacement := rust_property_replacement(property) {
									out << replacement.bytes()
									i = int(end)
									escaped = false
									continue
								}
							} else if body := rust_property_class_body(property) {
								out << negated_backend_class(body, config).bytes()
								i = int(end)
								escaped = false
								continue
							}
						} else if i + 3 <= pattern.len && pattern[i..i + 3] == r'\pL' {
							out << letter_backend_class().bytes()
							i += 3
							escaped = false
							continue
						}
					}
					else {}
				}
			}
		}
		if !escaped && !in_class && is_possessive_single_quantifier(pattern, i) {
			out << ch
			i += 2
			escaped = false
			continue
		}
		if !escaped && !in_class && ch == `{` {
			if end := possessive_braced_quantifier_end(pattern, i) {
				out << pattern[i..int(end) + 1].bytes()
				i = int(end) + 2
				escaped = false
				continue
			}
		}
		if !escaped && i + 7 <= pattern.len && ch == `\\` && pattern[i + 2] == `{`
			&& pattern[i + 3..i + 6] == 'Any' && pattern[i + 6] == `}` {
			if pattern[i + 1] == `p` {
				out << '(?:.|\n|\r)'.bytes()
				i += 7
				escaped = false
				continue
			}
			if pattern[i + 1] == `P` {
				out << r'(?!)'.bytes()
				i += 7
				escaped = false
				continue
			}
		}
		out << ch
		escaped = !escaped && ch == `\\`
		i++
	}
	return out.bytestr()
}

fn matching_group_end(pattern string, start int) ?usize {
	mut depth := 0
	mut escaped := false
	mut in_class := false
	for i := start; i < pattern.len; i++ {
		ch := pattern[i]
		if escaped {
			escaped = false
			continue
		}
		if ch == `\\` {
			escaped = true
			continue
		}
		if in_class {
			if ch == `]` {
				in_class = false
			}
			continue
		}
		if ch == `[` {
			in_class = true
			continue
		}
		if ch == `(` {
			depth++
			continue
		}
		if ch == `)` {
			depth--
			if depth == 0 {
				return usize(i)
			}
		}
	}
	return none
}

fn rust_word_boundary_variant_end(pattern string, i int) ?usize {
	variants := [r'\b{start}', r'\b{end}', r'\b{start-half}', r'\b{end-half}']
	for variant in variants {
		if i + variant.len <= pattern.len && pattern[i..i + variant.len] == variant {
			return usize(i + variant.len)
		}
	}
	return none
}

fn rust_property_escape_end(pattern string, i int) ?usize {
	if i + 3 >= pattern.len || pattern[i] != `\\` || (pattern[i + 1] != `p`
		&& pattern[i + 1] != `P`) || pattern[i + 2] != `{` {
		return none
	}
	mut end := i + 3
	for end < pattern.len && pattern[end] != `}` {
		end++
	}
	if end >= pattern.len {
		return none
	}
	return usize(end + 1)
}

fn rust_property_replacement(property string) ?string {
	if property.to_lower() == 'ascii' {
		return ascii_backend_class()
	}
	if body := rust_property_class_body(property) {
		return '[${body}]'
	}
	return none
}

fn rust_property_class_body(property string) ?string {
	match property.to_lower() {
		'ascii' { return ascii_backend_class_body() }
		'l', 'letter' { return letter_backend_class_body() }
		'gc=lu', 'general_category=lu', 'uppercaseletter' { return 'A-ZΑ-Ϋ' }
		'greek', 'script=greek', 'sc=greek' { return 'Α-Ͽ' }
		else { return none }
	}
}

fn word_backend_class(config Config) string {
	return '[${word_backend_class_body(config)}]'
}

fn word_backend_class_body(config Config) string {
	if config.unicode {
		return 'A-Za-z0-9_À-ÖØ-öø-ÿͰ-Ͽ'
	}
	return 'A-Za-z0-9_'
}

fn letter_backend_class() string {
	return '[${letter_backend_class_body()}]'
}

fn letter_backend_class_body() string {
	return 'A-Za-zÀ-ÖØ-öø-ÿͰ-Ͽ'
}

fn ascii_backend_class() string {
	return '[${ascii_backend_class_body()}]'
}

fn ascii_backend_class_body() string {
	mut out := []u8{cap: 8}
	out << `\t`
	out << `\r`
	out << ' -~'.bytes()
	return out.bytestr()
}

fn negated_backend_class(excluded string, config Config) string {
	mut out := '[^${excluded}'
	if line_term := config.line_terminator {
		if line_term.is_crlf() {
			out += r'\r\n'
		} else {
			out += escaped_class_byte(line_term.as_byte())
		}
	}
	out += ']'
	return out
}

fn escaped_class_byte(byte u8) string {
	match byte {
		`\\`, `]`, `-`, `^` { return '\\${byte.ascii_str()}' }
		else { return byte.ascii_str() }
	}
}

fn is_extended_whitespace(b u8) bool {
	return b == ` ` || b == `\t` || b == `\n` || b == `\r` || b == `\f`
}

fn is_possessive_single_quantifier(pattern string, i int) bool {
	return pattern[i] in [`*`, `+`, `?`] && i + 1 < pattern.len && pattern[i + 1] == `+`
}

fn possessive_braced_quantifier_end(pattern string, i int) ?usize {
	if pattern[i] != `{` {
		return none
	}
	mut j := i + 1
	mut saw_digit := false
	for j < pattern.len && pattern[j] >= `0` && pattern[j] <= `9` {
		saw_digit = true
		j++
	}
	if !saw_digit {
		return none
	}
	if j < pattern.len && pattern[j] == `,` {
		j++
		for j < pattern.len && pattern[j] >= `0` && pattern[j] <= `9` {
			j++
		}
	}
	if j + 1 < pattern.len && pattern[j] == `}` && pattern[j + 1] == `+` {
		return usize(j)
	}
	return none
}

fn validate_rust_regex_syntax(pattern string, config Config) ! {
	mut i := 0
	mut in_class := false
	for i < pattern.len {
		ch := pattern[i]
		if ch == `\\` {
			if i + 1 >= pattern.len {
				return
			}
			next := pattern[i + 1]
			if is_pcre_only_escape(next) {
				return Error.regex('unsupported escape sequence')
			}
			if !in_class && !config.octal && next >= `0` && next <= `9` {
				return Error.regex('backreferences are not supported')
			}
			i += 2
			continue
		}
		if in_class {
			if ch == `]` {
				in_class = false
			} else if i + 1 < pattern.len
				&& ((ch == `&` && pattern[i + 1] == `&`) || (ch == `-` && pattern[i + 1] == `-`)
				|| (ch == `~` && pattern[i + 1] == `~`)) {
				return Error.regex('character class set operations are not supported')
			}
			i++
			continue
		}
		if ch == `[` {
			if replacement := normalize_class_set_operation_at(pattern, i, config) {
				i = replacement.next
				continue
			}
			in_class = true
			i++
			continue
		}
		if ch == `{` && i + 1 < pattern.len && pattern[i + 1] == `,` {
			return Error.regex('repetition quantifier expects a valid decimal')
		}
		if ch == `(` && i + 1 < pattern.len && pattern[i + 1] == `*` {
			return Error.regex('unsupported regex group syntax')
		}
		if ch == `(` && i + 2 < pattern.len && pattern[i + 1] == `?` {
			kind := pattern[i + 2]
			if kind == `=` || kind == `!` {
				return Error.regex('look-around is not supported')
			}
			if kind == `<` && i + 3 < pattern.len && (pattern[i + 3] == `=`
				|| pattern[i + 3] == `!`) {
				return Error.regex('look-around is not supported')
			}
			if kind == `P` && i + 3 < pattern.len && (pattern[i + 3] == `=`
				|| pattern[i + 3] == `>`) {
				return Error.regex('backreferences are not supported')
			}
			if is_pcre_only_group_kind(kind) {
				return Error.regex('unsupported regex group syntax')
			}
		}
		i++
	}
}

fn is_pcre_only_escape(ch u8) bool {
	return ch in [`C`, `G`, `K`, `N`, `R`, `X`, `Z`, `g`, `h`, `H`, `k`, `V`]
}

fn is_pcre_only_group_kind(ch u8) bool {
	return ch in [`#`, `&`, `'`, `(`, `>`, `|`]
}

/// Returns true if the given literal string contains any byte from the line
/// terminator given.
fn has_line_terminator(lineterm matcher.LineTerminator, literal string) bool {
	if lineterm.is_crlf() {
		return literal.contains_u8(`\r`) || literal.contains_u8(`\n`)
	}
	return literal.contains_u8(lineterm.as_byte())
}

fn is_regex_meta_character(ch rune) bool {
	return ch in [`\\`, `.`, `+`, `*`, `?`, `(`, `)`, `|`, `[`, `]`, `{`, `}`, `^`, `$`,
		`#`, `&`, `-`, `~`]
}

fn escape_regex(literal string) string {
	mut out := []u8{cap: literal.len}
	for byte in literal.bytes() {
		match byte {
			`\\`, `.`, `+`, `*`, `?`, `(`, `)`, `|`, `[`, `]`, `{`, `}`, `^`, `$`, `#`,
			`&`, `-`, `~` {
				out << `\\`
				out << byte
			}
			else {
				out << byte
			}
		}
	}
	return out.bytestr()
}

fn strip_ignored_whitespace(pattern string) string {
	mut out := []u8{cap: pattern.len}
	mut i := 0
	mut in_class := false
	mut escaped := false
	for i < pattern.len {
		byte := pattern[i]
		if escaped {
			out << byte
			escaped = false
			i++
			continue
		}
		if byte == `\\` {
			out << byte
			escaped = true
			i++
			continue
		}
		if byte == `[` {
			in_class = true
			out << byte
			i++
			continue
		}
		if byte == `]` {
			in_class = false
			out << byte
			i++
			continue
		}
		if !in_class && byte == `#` {
			for i < pattern.len && pattern[i] != `\n` {
				i++
			}
			continue
		}
		if !in_class && byte in [` `, `\t`, `\n`, `\r`, `\v`, `\f`] {
			i++
			continue
		}
		out << byte
		i++
	}
	return out.bytestr()
}

fn ban_check(pattern string, byte u8) ! {
	mut i := 0
	for i < pattern.len {
		if pattern[i] == byte {
			return Error.new(ErrorKind.banned(byte))
		}
		if pattern[i] == `[` {
			class_set, ok, class_pos := parse_class_set(pattern, i + 1)
			if ok {
				mut count := 0
				for present in class_set {
					if present {
						count++
					}
				}
				if count == 1 && class_set[int(byte)] {
					return Error.new(ErrorKind.banned(byte))
				}
				i = class_pos
				continue
			}
		}
		if pattern[i] == `\\` {
			has_byte, escaped, next := parse_escape_byte(pattern, i)
			if has_byte && escaped == byte {
				return Error.new(ErrorKind.banned(byte))
			}
			i = next
			continue
		}
		i++
	}
}

// V-specific parser helper for class atoms in the port's local pattern checks.
struct ClassAtom {
	set        []bool
	single     u8
	has_single bool
	ok         bool
}

struct PatternReplacement {
	text string
	next int
}

fn normalize_posix_alpha_class_at(pattern string, start int, config Config) ?PatternReplacement {
	if start + 11 <= pattern.len && pattern[start..start + 11] == '[[:alpha:]]' {
		return PatternReplacement{
			text: '[A-Za-z]'
			next: start + 11
		}
	}
	prefix := '[^[:alpha:'
	if start + prefix.len > pattern.len || pattern[start..start + prefix.len] != prefix {
		return none
	}
	mut i := start + prefix.len
	for i + 1 < pattern.len {
		if pattern[i] == `]` && pattern[i + 1] == `]` {
			return PatternReplacement{
				text: negated_backend_class('A-Za-z', config)
				next: i + 2
			}
		}
		i++
	}
	return none
}

fn normalize_class_set_operation_at(pattern string, start int, config Config) ?PatternReplacement {
	if start >= pattern.len || pattern[start] != `[` {
		return none
	}
	end := find_class_end_nested(pattern, start) or { return none }
	body := pattern[start + 1..end]
	if !body.contains('&&') && !body.contains('--') && !body.contains('~~') {
		return none
	}
	class_set, ok, next := parse_class_set_expression(pattern, start + 1, end)
	if !ok || next != end {
		return none
	}
	mut stripped := class_set.clone()
	if line_term := config.line_terminator {
		if line_term.is_crlf() {
			stripped[int(`\r`)] = false
			stripped[int(`\n`)] = false
		} else {
			stripped[int(line_term.as_byte())] = false
		}
	}
	return PatternReplacement{
		text: byte_class_to_backend_pattern(stripped)
		next: end + 1
	}
}

fn find_class_end_nested(pattern string, start int) ?int {
	if start >= pattern.len || pattern[start] != `[` {
		return none
	}
	mut i := start + 1
	if i < pattern.len && pattern[i] == `^` {
		i++
	}
	for i < pattern.len {
		if pattern[i] == `\\` {
			i = skip_regex_escape(pattern, i)
			continue
		}
		if i + 1 < pattern.len && pattern[i] == `[` && pattern[i + 1] == `:` {
			mut posix_end := i + 2
			for posix_end + 1 < pattern.len {
				if pattern[posix_end] == `:` && pattern[posix_end + 1] == `]` {
					i = posix_end + 2
					break
				}
				posix_end++
			}
			if posix_end + 1 >= pattern.len {
				return none
			}
			continue
		}
		if pattern[i] == `[` {
			nested_end := find_class_end_nested(pattern, i) or { return none }
			i = nested_end + 1
			continue
		}
		if pattern[i] == `]` {
			return i
		}
		i++
	}
	return none
}

fn skip_regex_escape(pattern string, start int) int {
	if start + 1 >= pattern.len {
		return pattern.len
	}
	next := pattern[start + 1]
	if (next == `p` || next == `P`) && start + 2 < pattern.len && pattern[start + 2] == `{` {
		mut i := start + 3
		for i < pattern.len && pattern[i] != `}` {
			i++
		}
		if i < pattern.len {
			return i + 1
		}
	}
	return start + 2
}

fn parse_class_set_expression(pattern string, start int, end int) ([]bool, bool, int) {
	mut i := start
	mut negated := false
	if i < end && pattern[i] == `^` {
		negated = true
		i++
	}
	mut set, ok, next := parse_class_union_until_operation(pattern, i, end)
	if !ok {
		return set, false, next
	}
	i = next
	for i < end {
		if i + 1 >= end {
			return set, false, i
		}
		op := pattern[i..i + 2]
		if op != '&&' && op != '--' && op != '~~' {
			return set, false, i
		}
		right, right_ok, right_next := parse_class_union_until_operation(pattern, i + 2, end)
		if !right_ok {
			return set, false, right_next
		}
		apply_class_set_operation(mut set, right, op)
		i = right_next
	}
	if negated {
		invert_byte_class(mut set)
	}
	return set, true, i
}

fn parse_class_union_until_operation(pattern string, start int, end int) ([]bool, bool, int) {
	mut i := start
	mut set := empty_byte_class()
	mut saw_atom := false
	for i < end {
		if i + 1 < end && ((pattern[i] == `&` && pattern[i + 1] == `&`)
			|| (pattern[i] == `-` && pattern[i + 1] == `-`) || (pattern[i] == `~`
			&& pattern[i + 1] == `~`)) {
			break
		}
		start_atom, next_i := parse_class_atom_bounded(pattern, i, end)
		i = next_i
		if !start_atom.ok {
			return set, false, i
		}
		saw_atom = true
		if i < end && pattern[i] == `-` && !(i + 1 < end && pattern[i + 1] == `-`) {
			i++
			end_atom, after_end := parse_class_atom_bounded(pattern, i, end)
			i = after_end
			if !end_atom.ok {
				return set, false, i
			}
			if start_atom.has_single && end_atom.has_single {
				add_byte_range(mut set, start_atom.single, end_atom.single)
			} else {
				add_byte_class(mut set, start_atom.set)
				add_byte_class(mut set, end_atom.set)
			}
		} else {
			add_byte_class(mut set, start_atom.set)
		}
	}
	return set, saw_atom, i
}

fn parse_class_atom_bounded(pattern string, i int, end int) (ClassAtom, int) {
	if i >= end {
		return ClassAtom{}, i
	}
	if pattern[i] == `[` {
		if i + 11 <= pattern.len && pattern[i..i + 11] == '[[:alpha:]]' {
			mut set := empty_byte_class()
			add_byte_range(mut set, `A`, `Z`)
			add_byte_range(mut set, `a`, `z`)
			return ClassAtom{
				set: set
				ok:  true
			}, i + 11
		}
		nested_end := find_class_end_nested(pattern, i) or { return ClassAtom{}, end }
		nested, ok, next := parse_class_set_expression(pattern, i + 1, nested_end)
		if !ok || next != nested_end {
			return ClassAtom{}, nested_end + 1
		}
		return ClassAtom{
			set: nested
			ok:  true
		}, nested_end + 1
	}
	if pattern[i] == `\\` {
		set, has_single, single, ok, next := parse_escape_class(pattern, i)
		if next > end {
			return ClassAtom{}, end
		}
		return ClassAtom{
			set:        set
			single:     single
			has_single: has_single
			ok:         ok
		}, next
	}
	byte := pattern[i]
	mut set := empty_byte_class()
	set[int(byte)] = true
	return ClassAtom{
		set:        set
		single:     byte
		has_single: true
		ok:         true
	}, i + 1
}

fn apply_class_set_operation(mut set []bool, right []bool, op string) {
	for i, present in right {
		match op {
			'&&' {
				set[i] = set[i] && present
			}
			'--' {
				if present {
					set[i] = false
				}
			}
			'~~' {
				set[i] = set[i] != present
			}
			else {}
		}
	}
}

fn parse_class_set(pattern string, start int) ([]bool, bool, int) {
	mut i := start
	mut negated := false
	if i < pattern.len && pattern[i] == `^` {
		negated = true
		i++
	}
	mut set := empty_byte_class()
	for i < pattern.len {
		if pattern[i] == `]` {
			i++
			if negated {
				invert_byte_class(mut set)
			}
			return set, true, i
		}
		start_atom, next_i := parse_class_atom(pattern, i)
		i = next_i
		if !start_atom.ok {
			return set, false, i
		}
		if i < pattern.len && pattern[i] == `-` && i + 1 < pattern.len && pattern[i + 1] != `]` {
			i++
			end_atom, after_end := parse_class_atom(pattern, i)
			i = after_end
			if !end_atom.ok {
				return set, false, i
			}
			if start_atom.has_single && end_atom.has_single {
				add_byte_range(mut set, start_atom.single, end_atom.single)
			} else {
				add_byte_class(mut set, start_atom.set)
				add_byte_class(mut set, end_atom.set)
			}
		} else {
			add_byte_class(mut set, start_atom.set)
		}
	}
	return set, false, i
}

fn parse_class_atom(pattern string, i int) (ClassAtom, int) {
	if i >= pattern.len {
		return ClassAtom{}, i
	}
	if pattern[i] == `[` {
		nested, ok, next := parse_class_set(pattern, i + 1)
		return ClassAtom{
			set: nested
			ok:  ok
		}, next
	}
	if pattern[i] == `\\` {
		set, has_single, single, ok, next := parse_escape_class(pattern, i)
		return ClassAtom{
			set:        set
			single:     single
			has_single: has_single
			ok:         ok
		}, next
	}
	byte := pattern[i]
	mut set := empty_byte_class()
	set[int(byte)] = true
	return ClassAtom{
		set:        set
		single:     byte
		has_single: true
		ok:         true
	}, i + 1
}

fn parse_escape_class(pattern string, i int) ([]bool, bool, u8, bool, int) {
	if i + 1 >= pattern.len {
		return full_byte_class(), false, u8(0), false, pattern.len
	}
	next := pattern[i + 1]
	match next {
		`d` {
			mut set := empty_byte_class()
			add_byte_range(mut set, `0`, `9`)
			return set, false, u8(0), true, i + 2
		}
		`D` {
			mut set := full_byte_class()
			for byte := `0`; byte <= `9`; byte++ {
				set[int(byte)] = false
			}
			return set, false, u8(0), true, i + 2
		}
		`s` {
			mut set := empty_byte_class()
			for byte in [`\t`, `\n`, 0x0b, 0x0c, `\r`, ` `] {
				set[int(byte)] = true
			}
			return set, false, u8(0), true, i + 2
		}
		`S` {
			mut set := full_byte_class()
			for byte in [`\t`, `\n`, 0x0b, 0x0c, `\r`, ` `] {
				set[int(byte)] = false
			}
			return set, false, u8(0), true, i + 2
		}
		`w` {
			mut set := empty_byte_class()
			add_word_bytes(mut set)
			return set, false, u8(0), true, i + 2
		}
		`W` {
			mut set := full_byte_class()
			mut word := empty_byte_class()
			add_word_bytes(mut word)
			for index, present in word {
				if present {
					set[index] = false
				}
			}
			return set, false, u8(0), true, i + 2
		}
		`p`, `P` {
			if end := rust_property_escape_end(pattern, i) {
				property := pattern[i + 3..int(end) - 1]
				if mut set := rust_property_byte_class(property) {
					if next == `P` {
						invert_byte_class(mut set)
					}
					return set, false, u8(0), true, int(end)
				}
			} else if i + 3 <= pattern.len && pattern[i..i + 3] == r'\pL' {
				mut set := empty_byte_class()
				add_byte_range(mut set, `A`, `Z`)
				add_byte_range(mut set, `a`, `z`)
				return set, false, u8(0), true, i + 3
			}
			return full_byte_class(), false, u8(0), false, skip_regex_escape(pattern, i)
		}
		else {
			has_byte, byte, next_i := parse_escape_byte(pattern, i)
			if !has_byte {
				return full_byte_class(), false, u8(0), true, next_i
			}
			mut set := empty_byte_class()
			set[int(byte)] = true
			return set, true, byte, true, next_i
		}
	}
}

fn parse_escape_byte(pattern string, i int) (bool, u8, int) {
	if i + 1 >= pattern.len {
		return false, u8(0), pattern.len
	}
	next := pattern[i + 1]
	if escaped := escaped_byte(next) {
		return true, escaped, i + 2
	}
	if next == `x` {
		if i + 2 < pattern.len && pattern[i + 2] == `{` {
			mut end := i + 3
			for end < pattern.len && pattern[end] != `}` {
				end++
			}
			if end < pattern.len {
				value := parse_hex_u32(pattern[i + 3..end]) or { return false, u8(0), end + 1 }
				if value <= 0xff {
					return true, u8(value), end + 1
				}
				return false, u8(0), end + 1
			}
		}
		if i + 4 <= pattern.len {
			value := parse_hex_u32(pattern[i + 2..i + 4]) or { return false, u8(0), i + 4 }
			if value <= 0xff {
				return true, u8(value), i + 4
			}
			return false, u8(0), i + 4
		}
	}
	if next == `u` {
		if i + 2 < pattern.len && pattern[i + 2] == `{` {
			mut end := i + 3
			for end < pattern.len && pattern[end] != `}` {
				end++
			}
			if end < pattern.len {
				value := parse_hex_u32(pattern[i + 3..end]) or { return false, u8(0), end + 1 }
				if value <= 0xff {
					return true, u8(value), end + 1
				}
				return false, u8(0), end + 1
			}
		}
		if i + 6 > pattern.len {
			return false, u8(0), pattern.len
		}
		value := parse_hex_u32(pattern[i + 2..i + 6]) or { return false, u8(0), i + 6 }
		if value <= 0xff {
			return true, u8(value), i + 6
		}
		return false, u8(0), i + 6
	}
	if next == `U` && i + 10 <= pattern.len {
		value := parse_hex_u32(pattern[i + 2..i + 10]) or { return false, u8(0), i + 10 }
		if value <= 0xff {
			return true, u8(value), i + 10
		}
		return false, u8(0), i + 10
	}
	return true, next, i + 2
}

fn empty_byte_class() []bool {
	return []bool{len: 256}
}

fn full_byte_class() []bool {
	return []bool{len: 256, init: true}
}

fn invert_byte_class(mut set []bool) {
	for i in 0 .. set.len {
		set[i] = !set[i]
	}
}

fn add_byte_class(mut set []bool, other []bool) {
	for i, present in other {
		if present {
			set[i] = true
		}
	}
}

fn add_byte_range(mut set []bool, start u8, end u8) {
	if start <= end {
		for byte := start; byte <= end; byte++ {
			set[int(byte)] = true
		}
		return
	}
	for byte := end; byte <= start; byte++ {
		set[int(byte)] = true
	}
}

fn add_word_bytes(mut set []bool) {
	add_byte_range(mut set, `A`, `Z`)
	add_byte_range(mut set, `a`, `z`)
	add_byte_range(mut set, `0`, `9`)
	set[int(`_`)] = true
}

fn rust_property_byte_class(property string) ?[]bool {
	mut set := empty_byte_class()
	match property.to_lower() {
		'ascii' {
			add_byte_range(mut set, u8(0), u8(0x7f))
			return set
		}
		'l', 'letter' {
			add_byte_range(mut set, `A`, `Z`)
			add_byte_range(mut set, `a`, `z`)
			return set
		}
		'gc=lu', 'general_category=lu', 'uppercaseletter' {
			add_byte_range(mut set, `A`, `Z`)
			return set
		}
		else {
			return none
		}
	}
}

fn byte_class_to_backend_pattern(set []bool) string {
	mut any := false
	for present in set {
		if present {
			any = true
			break
		}
	}
	if !any {
		return r'(?!)'
	}
	mut out := []u8{cap: 64}
	out << `[`
	mut i := 0
	for i < set.len {
		if !set[i] {
			i++
			continue
		}
		start := u8(i)
		mut end := i
		for end + 1 < set.len && set[end + 1] {
			end++
		}
		append_backend_class_byte(mut out, start)
		if end > i {
			out << `-`
			append_backend_class_byte(mut out, u8(end))
		}
		i = end + 1
	}
	out << `]`
	return out.bytestr()
}

fn append_backend_class_byte(mut out []u8, byte u8) {
	match byte {
		`\\`, `]`, `-`, `^` {
			out << `\\`
			out << byte
		}
		`\n` {
			out << `\\`
			out << `n`
		}
		`\r` {
			out << `\\`
			out << `r`
		}
		`\t` {
			out << `\\`
			out << `t`
		}
		else {
			if byte < 0x20 || byte >= 0x7f {
				hex := '0123456789ABCDEF'
				out << `\\`
				out << `x`
				out << hex[int(byte >> 4)]
				out << hex[int(byte & 0x0f)]
			} else {
				out << byte
			}
		}
	}
}

fn strip_line_terminator_from_match(pattern string, line_term matcher.LineTerminator) !string {
	mut out := []u8{cap: pattern.len}
	mut i := 0
	mut in_class := false
	for i < pattern.len {
		byte := pattern[i]
		if byte == `[` {
			class, next := strip_class_line_terminator(pattern, i, line_term)!
			out << class.bytes()
			i = next
			continue
		}
		if byte == `]` {
			in_class = false
			out << byte
			i++
			continue
		}
		if byte == `\\` && i + 1 < pattern.len {
			next := pattern[i + 1]
			if next == `s` {
				if line_term_can_match_ascii_whitespace(line_term) {
					append_ascii_whitespace_class_without_line_term(mut out, line_term, true)
				} else {
					out << `\\`
					out << next
				}
				i += 2
				continue
			}
			has_byte, escaped, next_i := parse_escape_byte(pattern, i)
			if has_byte {
				if line_term_rejects_byte(line_term, escaped) {
					return Error.new(ErrorKind.not_allowed([escaped].bytestr()))
				}
			}
			for j in i .. next_i {
				out << pattern[j]
			}
			i = next_i
			continue
		}
		if !in_class && line_term_rejects_byte(line_term, byte) {
			return Error.new(ErrorKind.not_allowed([byte].bytestr()))
		}
		out << byte
		i++
	}
	return out.bytestr()
}

fn strip_class_line_terminator(pattern string, start int, line_term matcher.LineTerminator) !(string, int) {
	mut out := []u8{cap: pattern.len - start}
	out << `[`
	mut i := start + 1
	mut negated := false
	if i < pattern.len && pattern[i] == `^` {
		negated = true
		out << `^`
		i++
	}
	mut kept := 0
	mut excluded_line_term := false
	for i < pattern.len {
		if pattern[i] == `]` {
			if negated {
				if line_term.is_crlf() {
					if !excluded_line_term {
						out << `\\`
						out << `r`
						out << `\\`
						out << `n`
					}
				} else if !excluded_line_term {
					append_escaped_byte(mut out, line_term.as_byte())
				}
			} else if kept == 0 {
				return Error.new(ErrorKind.not_allowed(line_term.as_bytes().bytestr()))
			}
			out << `]`
			return out.bytestr(), i + 1
		}
		if pattern[i] == `\\` && i + 1 < pattern.len {
			next := pattern[i + 1]
			if next == `s` {
				if line_term_can_match_ascii_whitespace(line_term) {
					append_ascii_whitespace_class_without_line_term(mut out, line_term, false)
				} else {
					out << pattern[i]
					out << next
				}
				kept++
				i += 2
				continue
			}
			if is_byte_escape_start(next) {
				has_byte, escaped, next_i := parse_escape_byte(pattern, i)
				if has_byte && line_term_rejects_byte(line_term, escaped) {
					excluded_line_term = true
					i = next_i
					continue
				}
				for j in i .. next_i {
					out << pattern[j]
				}
				kept++
				i = next_i
				continue
			}
			if escaped := escaped_byte(next) {
				if line_term_rejects_byte(line_term, escaped) {
					excluded_line_term = true
					i += 2
					continue
				}
			}
			out << pattern[i]
			out << next
			kept++
			i += 2
			continue
		}
		if line_term_rejects_byte(line_term, pattern[i]) {
			excluded_line_term = true
			i++
			continue
		}
		out << pattern[i]
		kept++
		i++
	}
	return Error.new(ErrorKind.not_allowed(line_term.as_bytes().bytestr()))
}

fn is_byte_escape_start(byte u8) bool {
	return byte == `x` || byte == `u` || byte == `U`
}

fn line_term_can_match_ascii_whitespace(line_term matcher.LineTerminator) bool {
	if line_term.is_crlf() {
		return true
	}
	return line_term.as_byte() in [` `, `\t`, `\r`, u8(0x0b), u8(0x0c), `\n`]
}

fn append_ascii_whitespace_class_without_line_term(mut out []u8, line_term matcher.LineTerminator, wrap bool) {
	if wrap {
		out << `[`
	}
	for byte in [` `, `\t`, `\r`, u8(0x0b), u8(0x0c), `\n`] {
		if !line_term_rejects_byte(line_term, byte) {
			out << byte
		}
	}
	if wrap {
		out << `]`
	}
}

fn append_escaped_byte(mut out []u8, byte u8) {
	match byte {
		`\n` {
			out << `\\`
			out << `n`
		}
		`\r` {
			out << `\\`
			out << `r`
		}
		`\t` {
			out << `\\`
			out << `t`
		}
		else {
			out << byte
		}
	}
}

fn escaped_byte(byte u8) ?u8 {
	return match byte {
		`n` { u8(`\n`) }
		`r` { u8(`\r`) }
		`t` { u8(`\t`) }
		else { none }
	}
}

fn line_term_rejects_byte(line_term matcher.LineTerminator, byte u8) bool {
	if line_term.is_crlf() {
		return byte == `\r` || byte == `\n`
	}
	return byte == line_term.as_byte()
}
